import { Effect } from "effect";
import { Argument as Args, Command, Flag as Options } from "effect/unstable/cli";
import { defineDocsCommandContribution, deliverDomainResult, jsonDocument, type TerminalDeliverySink } from "./contribution.js";
import { addCaseIssue, addCaseRegression, auditCases, inventoryCases, listCases, refreshCaseRegression, renderCaseCommandError, renderCaseReceipt, retireCase, retireCaseIssue, retireCaseRegression, showCase } from "./test-case/cli-runtime.js";

const json = Options.boolean("json").pipe(Options.withDefault(false), Options.withDescription("Emit a machine-readable JSON receipt."));
const dryRun = Options.boolean("dry-run").pipe(Options.withDefault(false), Options.withDescription("Plan and validate without writing files."));
const inventory = Options.string("inventory").pipe(Options.optional, Options.withDescription("Managed inventory ID returned by docs test inventory."));
const inventoryOptions = { repo: Options.string("repo"), checkout: Options.string("checkout").pipe(Options.withDefault("HEAD")) };
const mutationOptions = { dryRun, json };
function run<A, E, R>(deliver: TerminalDeliverySink, program: Effect.Effect<A, E, R>, structured: boolean) { return deliverDomainResult(program, structured, { success: (value, asJson) => asJson ? jsonDocument(value) : renderCaseReceipt(value), failure: renderCaseCommandError }, deliver); }

function makeTestCommand(deliver: TerminalDeliverySink) {
  const inventoryCommand = Command.make("inventory", { ...inventoryOptions, json }, (o) => run(deliver, inventoryCases(o), o.json)).pipe(Command.withDescription("Prepare one declared isolated test suite, collect its native cases, and save a managed inventory."));
  const list = Command.make("list", { pattern: Args.string("pattern").pipe(Args.optional), history: Options.boolean("history").pipe(Options.withDefault(false)), inventory, json }, (o) => run(deliver, listCases(o), o.json)).pipe(Command.withDescription("List case selectors and current declaration annotations; optionally compare a managed inventory."));
  const show = Command.make("show", { selector: Args.string("path#caseId"), history: Options.boolean("history").pipe(Options.withDefault(false)), inventory, json }, (o) => run(deliver, showCase(o), o.json)).pipe(Command.withDescription("Show one exact case selector, its digest, contract, regressions, issues, and history."));
  const audit = Command.make("audit", { checkout: Options.string("checkout").pipe(Options.withDefault("HEAD")), json }, (o) => run(deliver, auditCases(o), o.json)).pipe(Command.withDescription("Prepare every declared test suite and report uncovered Use Cases, missing live-case relations, and orphaned relations."));
  const retireCaseCommand = Command.make("retire", { selector: Args.string("path#caseId"), reason: Options.string("reason"), ...mutationOptions }, (o) => run(deliver, retireCase(o), o.json)).pipe(Command.withDescription("Retire a case into its permanent tombstone."));
  const caseCommand = Command.make("case").pipe(Command.withDescription("Manage current source declarations."), Command.withSubcommands([retireCaseCommand]));
  const regressionAdd = Command.make("add", { selector: Args.string("path#caseId"), memory: Options.string("memory"), red: Options.string("red").pipe(Options.withDescription("Managed red evidence ID returned by the native adapter.")), takeover: Options.string("takeover").pipe(Options.withDescription("Managed reliability evidence ID returned by the native adapter.")), inventory: Options.string("inventory"), ...mutationOptions }, (o) => run(deliver, addCaseRegression(o), o.json)).pipe(Command.withDescription("Attach an open Problem only after managed red and complete takeover evidence validate for this inventoried case."));
  const regressionRefresh = Command.make("refresh", { selector: Args.string("path#caseId"), memory: Options.string("memory"), red: Options.string("red").pipe(Options.withDescription("Fresh managed red evidence ID returned by the native adapter.")), takeover: Options.string("takeover").pipe(Options.withDescription("Fresh managed reliability evidence ID returned by the native adapter.")), inventory: Options.string("inventory"), reason: Options.string("reason"), ...mutationOptions }, (o) => run(deliver, refreshCaseRegression(o), o.json)).pipe(Command.withDescription("Replace evidence for an existing current regression after current native evidence validation, preserving the previous index entry in history."));
  const regressionRetire = Command.make("retire", { selector: Args.string("path#caseId"), memory: Options.string("memory"), reason: Options.string("reason"), ...mutationOptions }, (o) => run(deliver, retireCaseRegression(o), o.json)).pipe(Command.withDescription("Retire a regression; resolved Problems must be reopened first."));
  const regression = Command.make("regression").pipe(Command.withDescription("Manage zero or more Problem regressions per case."), Command.withSubcommands([regressionAdd, regressionRefresh, regressionRetire]));
  const issueAdd = Command.make("add", { selector: Args.string("path#caseId"), url: Options.string("url"), provenance: Options.choice("provenance", ["direct"] as const), verificationReceipt: Options.string("verification-receipt").pipe(Options.optional, Options.withDescription("Injected already-verified read-only receipt for isolated fixtures.")), ...mutationOptions }, (o) => run(deliver, addCaseIssue(o), o.json)).pipe(Command.withDescription("Read-only verify a same-repository canonical non-PR Issue with direct case provenance, then attach it locally."));
  const issueRetire = Command.make("retire", { selector: Args.string("path#caseId"), url: Options.string("url"), reason: Options.string("reason"), ...mutationOptions }, (o) => run(deliver, retireCaseIssue(o), o.json)).pipe(Command.withDescription("Retire one current Issue relation without mutating GitHub."));
  const issue = Command.make("issue").pipe(Command.withDescription("Manage zero or more verified Issue relations per case."), Command.withSubcommands([issueAdd, issueRetire]));
  return Command.make("test").pipe(Command.withDescription("Manage runner-inventoried native cases and their declaration-owned relations."), Command.withSubcommands([inventoryCommand, audit, list, show, caseCommand, regression, issue]));
}
export const testCommandContribution = defineDocsCommandContribution({ name: "test", summary: "Manage runner-inventoried native case relations.", makeCommand: makeTestCommand });
