import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import { chromium, expect, type Browser } from '@playwright/test';
import { addPage, createDocument } from '../dist/documents.js';
import { initialize, LocalRepository } from '../dist/storage.js';
import { startViewServer, type ViewServerHandle } from '../dist/view-server.js';

// @concord-case browser-direct-access-retry-and-refresh
// @concord-contract docs/feature/web-workbench/use-case/use-web-workbench.md
test('browser opens and refreshes a deep link without credentials and retries initial load failures', async () => {
  const root = mkdtempSync(join(tmpdir(), 'concord-browser-open-'));
  let server: ViewServerHandle | undefined;
  let browser: Browser | undefined;
  try {
    execFileSync('git', ['init', '-q', root]);
    const repo = new LocalRepository(root, { initialize: true });
    try {
      initialize(repo, false, { testRoots: [] });
      createDocument(repo, 'feature', { id: 'web', title: 'Direct access fixture' });
      createDocument(repo, 'feature', {
        id: 'html',
        title: 'Raw HTML fixture',
        body: '# Raw HTML fixture\n\n<details><summary>More</summary>\n\nContent\n\n</details>\n',
      });
      for (let index = 0; index < 24; index += 1) createDocument(repo, 'feature', { id: `fixture-${index}`, title: `Navigation fixture ${index}` });
    } finally { repo.close(); }
    server = await startViewServer({ root, host: '127.0.0.1', port: 0 });
    const executablePath = process.env.CONCORD_BROWSER_PATH ?? (existsSync('/run/current-system/sw/bin/chromium') ? '/run/current-system/sw/bin/chromium' : undefined);
    browser = await chromium.launch({ headless: true, ...(executablePath ? { executablePath } : {}), args: ['--no-sandbox'] });
    const page = await browser.newPage();
    const authorizations: (string | undefined)[] = [];
    const errors: string[] = [];
    page.on('request', request => {
      if (new URL(request.url()).pathname.startsWith('/api/')) authorizations.push(request.headers().authorization);
    });
    page.on('pageerror', error => errors.push(error.message));
    await page.route('**/api/workspace', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ ok: false, error: 'FixtureUnavailable', message: '工作区暂时不可用' }) }));
    const url = `http://127.0.0.1:${server.port}/features/web`;
    await page.goto(url);
    await expect(page.getByRole('alert')).toHaveText('工作区暂时不可用');
    await expect(page.getByLabel('访问密钥', { exact: true })).toHaveCount(0);
    await page.unroute('**/api/workspace');
    await page.getByRole('button', { name: '重试', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Direct access fixture', exact: true })).toBeVisible();
    await expect(page).toHaveURL(url);
    const contentNavigation = page.getByRole('navigation', { name: '内容导航', exact: true });
    assert.equal(await contentNavigation.evaluate(element => element.parentElement!.scrollHeight > element.parentElement!.clientHeight), true);
    const pagePane = page.locator('.document-workspace > .page');
    await contentNavigation.evaluate(element => { element.parentElement!.scrollTop = 160; });
    assert.equal(await contentNavigation.evaluate(element => element.parentElement!.scrollTop), 160);
    assert.equal(await pagePane.evaluate(element => element.scrollTop), 0);
    const themeToggle = page.getByRole('button', { name: '切换至深色主题', exact: true });
    await expect(themeToggle).toBeVisible();
    await themeToggle.click();
    await expect(page.locator('html')).toHaveClass(/dark/);
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
    assert.equal(await page.evaluate(() => localStorage.getItem('concord-theme')), 'dark');
    await page.reload();
    await expect(page.getByRole('heading', { name: 'Direct access fixture', exact: true })).toBeVisible();
    await expect(page).toHaveURL(url);
    await expect(page.locator('html')).toHaveClass(/dark/);
    await expect(page.getByRole('button', { name: '切换至浅色主题', exact: true })).toBeVisible();
    await expect(page.getByTestId('document-header').getByRole('button', { name: '重新载入', exact: true })).toBeVisible();
    await expect(page.locator('.editor-shell > .editor-shell__bar')).toHaveCount(0);
    await contentNavigation.getByRole('link', { name: 'Raw HTML fixture', exact: true }).click();
    await expect(page.getByText('已切换为原文编辑', { exact: true })).toBeVisible();
    await expect(page.getByLabel('Markdown 原文', { exact: true })).toContainText('<details>');
    await expect(page.getByText('Unexpected Application Error!', { exact: true })).toHaveCount(0);
    assert.ok(authorizations.length > 0);
    assert.ok(authorizations.every(value => value === undefined));
    assert.deepEqual(errors, []);
  } finally {
    await browser?.close();
    await server?.close();
    rmSync(root, { recursive: true, force: true });
  }
});

// @concord-case browser-authoring-and-git-workflow
// @concord-contract docs/feature/web-workbench/use-case/use-web-workbench.md
test('real browser creates a Feature, edits Markdown, preserves conflicts and opens Git changes', async () => {
  const root=mkdtempSync(join(tmpdir(),'concord-browser-'));
  let server: ViewServerHandle|undefined;
  let browser: Browser|undefined;
  try {
    execFileSync('git',['init','-q',root]);
    const repo=new LocalRepository(root,{initialize:true});
    try {
      initialize(repo,false,{testRoots:['test'],sourceRoots:['src']});
      createDocument(repo,'engineering',{id:'build',title:'Build workflow'});
      const engineeringPath=join(root,'docs/engineering/build/README.md');
      writeFileSync(engineeringPath,`${readFileSync(engineeringPath,'utf8')}\n\`\`\`mermaid\nflowchart LR\n  Source --> Result\n\`\`\`\n`);
      addPage(repo,'engineering','build','architecture');
      createDocument(repo,'roadmap',{id:'future',title:'Future direction',pages:['architecture']});
      createDocument(repo,'design',{id:'options',title:'Design options',alternatives:['first','second'],pages:['architecture']});
      createDocument(repo,'research',{id:'study',title:'Research study',observedAt:'2026-09-14',sources:['Local observations']});
    } finally {repo.close();}
    mkdirSync(join(root,'src'));
    writeFileSync(join(root,'src/demo.ts'),'export const demo = 1;\n');
    server=await startViewServer({root,host:'127.0.0.1',port:0});
    const executablePath=process.env.CONCORD_BROWSER_PATH ?? (existsSync('/run/current-system/sw/bin/chromium')?'/run/current-system/sw/bin/chromium':undefined);
    browser=await chromium.launch({headless:true,...(executablePath?{executablePath}:{}),args:['--no-sandbox']});
    const page=await browser.newPage({viewport:{width:1440,height:1000}});
    const errors:string[]=[];
    page.on('pageerror',error=>errors.push(error.message));
    await page.goto(`http://127.0.0.1:${server.port}/features`);
    await expect(page.getByRole('heading',{name:'Feature',exact:true})).toBeVisible();
    assert.equal(await page.getByRole('link',{name:'Feature',exact:true}).evaluate(element=>getComputedStyle(element).display),'flex','sidebar must forward shadcn classes to its links');
    assert.equal(await page.locator('[data-slot="sidebar"]').getByRole('link',{name:'Use Case',exact:true}).count(),0);
    const sidebar=page.locator('[data-slot="sidebar"]');
    const navigation=page.getByRole('navigation',{name:'内容导航',exact:true});
    for (const [category,title,section] of [['Engineering','Build workflow','engineering'],['Roadmap','Future direction','roadmap'],['Design','Design options','design'],['Research','Research study','research']] as const) {
      await sidebar.getByRole('link',{name:category,exact:true}).click();
      const list=navigation.getByRole('list',{name:`${category} 列表`,exact:true});
      await expect(sidebar.getByRole('link',{name:title,exact:true})).toHaveCount(0);
      await list.getByRole('link',{name:title,exact:true}).click();
      await expect(page).toHaveURL(new RegExp(`/${section}/`));
      await expect(list.getByRole('link',{name:title,exact:true})).toHaveAttribute('aria-current','page');
      if (category === 'Engineering') {
        const diagram=page.getByLabel('Mermaid 图表预览').locator('svg');
        await expect(diagram).toBeVisible();
        const initialDiagram=await diagram.evaluate(element=>element.outerHTML);
        await page.locator('.theme-toggle').click();
        await expect.poll(()=>diagram.evaluate(element=>element.outerHTML)).not.toBe(initialDiagram);
      }
      if (category !== 'Research') {
        const supportingPage=page.getByTestId('document-file-tree').getByRole('button',{name:category === 'Design' ? 'plans/first/architecture.md' : 'architecture.md',exact:true});
        await supportingPage.click();
        await expect(page.locator('[contenteditable="true"]').first()).toBeVisible();
      }
      await expect(list.getByRole('link',{name:title,exact:true})).toBeVisible();
    }
    await sidebar.getByRole('link',{name:'Feature',exact:true}).click();
    await page.getByRole('button',{name:'新建 Feature',exact:true}).click();
    await page.getByLabel('Feature ID',{exact:true}).fill('browser-feature');
    await page.getByLabel('Feature 标题',{exact:true}).fill('Browser authoring');
    await page.getByRole('checkbox',{name:'Architecture',exact:true}).check();
    await page.getByRole('checkbox',{name:'Library',exact:true}).check();
    await page.getByLabel('初始正文',{exact:true}).fill('# Browser authoring\n\nOriginal paragraph.\n');
    await page.getByRole('button',{name:'创建',exact:true}).click();
    assert.equal(existsSync(join(root,'docs/feature/browser-feature/cli.md')),false);
    await page.getByRole('link').filter({hasText:'Browser authoring'}).first().click();
    await page.getByRole('button',{name:'新建 Feature',exact:true}).click();
    await page.getByLabel('Feature ID',{exact:true}).fill('alternate-feature');
    await page.getByLabel('Feature 标题',{exact:true}).fill('Alternate Feature');
    await page.getByRole('button',{name:'创建',exact:true}).click();
    const featureList=navigation.getByRole('list',{name:'Feature 列表',exact:true});
    await featureList.getByRole('link',{name:'Alternate Feature',exact:true}).click();
    await expect(page.getByRole('heading',{name:'Alternate Feature',exact:true}).first()).toBeVisible();
    await expect(featureList.getByRole('link',{name:'Browser authoring',exact:true})).toBeVisible();
    await featureList.getByRole('link',{name:'Browser authoring',exact:true}).click();
    await expect(featureList.getByRole('link',{name:'Alternate Feature',exact:true})).toBeVisible();
    await expect(page.locator('.page .card-grid')).toHaveCount(0);
    await navigation.getByLabel('筛选 Feature',{exact:true}).fill('browser-feature');
    await expect(featureList.getByRole('link',{name:'Alternate Feature',exact:true})).toHaveCount(0);
    await navigation.getByLabel('筛选 Feature',{exact:true}).fill('');
    const editor=page.locator('[contenteditable="true"]').first();
    await expect(editor).toBeVisible();
    await expect(page.locator('.page .page-header')).toHaveCount(0);
    await expect(page.locator('.editor-shell__bar .eyebrow')).toHaveCount(0);
    const path=join(root,'docs/feature/browser-feature/README.md');
    const original=readFileSync(path,'utf8');
    await expect(page.getByRole('button',{name:'保存',exact:true})).toHaveCount(0);
    assert.equal(readFileSync(path,'utf8'),original,'loading must not normalize the file');
    await editor.fill('Browser edited paragraph.');
    await page.getByRole('tab',{name:'关系',exact:true}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await page.getByRole('tab',{name:'正文',exact:true}).click();
    await expect(editor).toContainText('Browser edited paragraph.');
    await expect.poll(()=>readFileSync(path,'utf8')).toContain('Browser edited paragraph.');
    await page.getByRole('tab',{name:'元数据',exact:true}).click();
    await page.getByLabel('文档标题',{exact:true}).fill('Browser authoring renamed');
    await expect(featureList.getByRole('link',{name:'Browser authoring renamed',exact:true})).toBeVisible();
    await page.getByLabel('文档标题',{exact:true}).fill('Browser authoring');
    await expect(featureList.getByRole('link',{name:'Browser authoring',exact:true})).toBeVisible();
    await page.getByRole('tab',{name:'正文',exact:true}).click();
    await expect(editor).toBeVisible();
    let releaseSave: (() => void) | undefined;
    const holdSave = new Promise<void>(resolve => { releaseSave = resolve; });
    let writes = 0;
    await page.route('**/api/action', async route => {
      const action = route.request().postDataJSON() as { action?: string; path?: string };
      if (action.action === 'document.set' && action.path === 'docs/feature/browser-feature/README.md') {
        writes++;
        if (writes === 1) await holdSave;
      }
      await route.continue();
    });
    await editor.fill('Browser edited paragraph. First revision.');
    await expect.poll(() => writes).toBe(1);
    await editor.fill('Browser edited paragraph. Latest revision.');
    assert.equal(writes, 1, 'later input waits behind the in-flight save');
    releaseSave?.();
    await expect.poll(()=>readFileSync(path,'utf8')).toContain('Latest revision.');
    assert.equal(writes, 2);
    await page.unroute('**/api/action');
    await editor.fill('Unsaved browser draft.');
    const disk=readFileSync(path,'utf8').replace('Browser edited paragraph.','External editor wins.');
    writeFileSync(path,disk);
    await expect(page.getByRole('dialog')).toBeVisible();
    await expect(page.getByRole('dialog')).toContainText('Unsaved browser draft.');
    assert.equal(readFileSync(path,'utf8'),disk,'conflict must preserve the external edit');
    await page.getByRole('button',{name:'丢弃草稿并载入',exact:true}).click();
    await page.getByRole('button',{name:'新建 Use Case',exact:true}).click();
    await page.getByLabel('Use Case ID',{exact:true}).fill('browser-flow');
    await page.getByLabel('Use Case 标题',{exact:true}).fill('Nested browser flow');
    await page.getByRole('button',{name:'创建',exact:true}).click();
    const nestedCase=page.locator('.feature-use-cases').getByRole('link').filter({hasText:'Nested browser flow'});
    await expect(nestedCase).toBeVisible();
    await expect(sidebar.getByRole('link',{name:'Nested browser flow',exact:true})).toHaveCount(0);
    const primaryBounds=await sidebar.boundingBox();
    const contentBounds=await navigation.boundingBox();
    assert.ok(primaryBounds && contentBounds && contentBounds.x >= primaryBounds.x + primaryBounds.width, 'content navigation occupies its own column');
    assert.match(readFileSync(join(root,'docs/feature/browser-feature/use-case/browser-flow.md'),'utf8'),/feature: docs\/feature\/browser-feature\/README\.md/);
    await editor.fill('External editor wins. Flushed from Feature.');
    await editor.evaluate(element => element.setAttribute('data-feature-editor-instance', 'preserved'));
    await nestedCase.click();
    const drawer=page.getByRole('dialog',{name:'Nested browser flow',exact:true});
    await expect(drawer).toBeVisible();
    await expect(page.locator('.page [inert]')).toContainText('External editor wins. Flushed from Feature.');
    await expect(drawer.getByRole('heading',{name:'Nested browser flow',exact:true}).first()).toBeVisible();
    await expect.poll(async () => {
      const bounds=await drawer.boundingBox();
      return bounds ? Math.round(bounds.x + bounds.width) : 0;
    }).toBe(1440);
    await page.goBack();
    await expect(drawer).toHaveCount(0);
    await expect(editor).toContainText('External editor wins.');
    await expect(editor).toHaveAttribute('data-feature-editor-instance', 'preserved');
    await page.locator('.feature-use-cases').getByRole('link').filter({hasText:'Nested browser flow'}).click();
    const drawerEditor=drawer.locator('[contenteditable="true"]').first();
    await expect(drawerEditor).toBeVisible();
    await drawerEditor.fill('Saved Use Case body.');
    await expect.poll(()=>readFileSync(join(root,'docs/feature/browser-feature/use-case/browser-flow.md'),'utf8')).toContain('Saved Use Case body.');
    await drawerEditor.fill('Saved on drawer close.');
    await drawer.getByRole('button',{name:'Close',exact:true}).click();
    await expect(drawer).toHaveCount(0);
    assert.ok(readFileSync(join(root,'docs/feature/browser-feature/use-case/browser-flow.md'),'utf8').includes('Saved on drawer close.'));
    await nestedCase.click();
    await page.reload();
    await expect(drawer).toBeVisible();
    await expect(drawer.locator('[contenteditable="true"]').first()).toBeVisible();
    await page.keyboard.press('Escape');
    await expect(drawer).toHaveCount(0);
    await expect(editor).toContainText('External editor wins.');
    const documentTree=page.getByTestId('document-file-tree');
    await documentTree.getByRole('button',{name:'architecture.md',exact:true}).click();
    await editor.fill('Architecture from browser.');
    const documentPane=page.getByTestId('document-file-preview');
    await documentPane.evaluate(element=>{element.scrollTop=500;});
    await documentTree.evaluate(element=>{element.scrollTop=80;});
    const treeScrollBefore=await documentTree.evaluate(element=>element.scrollTop);
    await documentTree.getByRole('button',{name:'library.md',exact:true}).click();
    await expect.poll(()=>documentPane.evaluate(element=>element.scrollTop)).toBe(0);
    assert.equal(await documentTree.evaluate(element=>element.scrollTop),treeScrollBefore);
    const outerPage=page.locator('.document-workspace > .page');
    assert.equal(await outerPage.evaluate(element=>element.scrollHeight===element.clientHeight),true);
    assert.equal(await outerPage.evaluate(element=>getComputedStyle(element).scrollbarWidth),'none');
    assert.equal(await page.getByRole('tablist',{name:'文档详情'}).evaluate(element=>getComputedStyle(element).scrollbarWidth),'none');
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await expect.poll(()=>readFileSync(join(root,'docs/feature/browser-feature/architecture.md'),'utf8')).toContain('Architecture from browser.');
    await page.getByRole('link',{name:'Git 变更',exact:true}).click();
    await expect(page.getByRole('heading',{name:'工作树变更',exact:true})).toBeVisible();
    const gitTree = page.getByRole('navigation',{name:'Git 文件树',exact:true});
    await expect(gitTree.getByRole('button',{name:'docs/feature/browser-feature/README.md',exact:true})).toBeVisible();
    await gitTree.getByRole('button',{name:'docs/feature/browser-feature/README.md',exact:true}).click();
    await expect(page.locator('[data-git-diff]')).toContainText('External editor wins.');
    await expect(page.getByRole('dialog')).toHaveCount(0);
    const treeBounds = await gitTree.boundingBox();
    const diffBounds = await page.locator('[data-git-diff]').boundingBox();
    assert.ok(treeBounds && diffBounds && diffBounds.x >= treeBounds.x + treeBounds.width, 'Git diff stays beside the file tree');
    await gitTree.getByRole('button',{name:'docs 目录',exact:true}).click();
    await expect(gitTree.getByRole('button',{name:'docs/feature/browser-feature/README.md',exact:true})).toBeHidden();
    await gitTree.getByRole('button',{name:'docs 目录',exact:true}).click();
    writeFileSync(path,readFileSync(path,'utf8').replace('External editor wins.','Refreshed Git content.'));
    await page.getByRole('button',{name:'刷新',exact:true}).click();
    await expect(page.locator('[data-git-diff]')).toContainText('Refreshed Git content.');
    await page.keyboard.press('Escape');
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await page.getByRole('link',{name:'项目设置',exact:true}).click();
    await expect(page.getByLabel('Project ID',{exact:true})).not.toBeEditable();
    await page.getByLabel('运行超时',{exact:true}).fill('11111');
    await expect.poll(()=>JSON.parse(readFileSync(join(root,'concord.json'),'utf8')).runner.timeoutMs).toBe(11111);
    await page.getByLabel('源码目录',{exact:true}).fill('src\n');
    await expect(page.getByLabel('源码目录',{exact:true})).toHaveValue('src\n');
    // Wait for the preceding save/readback to finish before introducing an external edit.
    await expect(page.getByLabel('源码目录',{exact:true})).toHaveValue('src');
    await expect(page.getByRole('status')).toContainText('已自动保存');
    await page.getByLabel('运行超时',{exact:true}).fill('12345');
    const configPath=join(root,'concord.json');
    const config=JSON.parse(readFileSync(configPath,'utf8'));
    config.runner.timeoutMs=54321;
    const externalConfig=`${JSON.stringify(config,null,2)}\n`;
    writeFileSync(configPath,externalConfig);
    await page.waitForResponse(response=>response.url().endsWith('/api/workspace')&&response.ok());
    await expect(page.locator('.form-error').first()).toBeVisible();
    await expect(page.getByLabel('运行超时',{exact:true})).toHaveValue('12345');
    assert.equal(readFileSync(configPath,'utf8'),externalConfig,'polled digests must not let stale config overwrite disk');
    await page.getByRole('tab',{name:'高级 JSON',exact:true}).click();
    await page.getByLabel('高级项目配置 JSON',{exact:true}).fill('{}');
    await page.getByRole('tab',{name:'常用设置',exact:true}).click();
    await expect(page.getByLabel('高级项目配置 JSON',{exact:true})).toHaveValue('{}');
    await expect(page.locator('.form-error').first()).toBeVisible();
    await sidebar.getByRole('link',{name:'Feature',exact:true}).click();
    await expect(page.getByRole('dialog')).toBeVisible();
    await page.getByRole('button',{name:'丢弃并离开',exact:true}).click();
    await expect(navigation).toBeVisible();
    await navigation.getByRole('link',{name:'Browser authoring',exact:true}).click();
    writeFileSync(join(root,'src/demo.ts'),'// @concord-file browser-demo\n// @concord-implements docs/feature/browser-feature/README.md\nexport const demo = 1;\n');
    mkdirSync(join(root,'test'),{recursive:true});
    writeFileSync(join(root,'test/demo.test.ts'),"import test from 'node:test';\n// @concord-case browser-added-test\n// @concord-contract docs/feature/browser-feature/use-case/browser-flow.md\ntest('Added browser test', () => {});\n" + Array.from({length:100},(_,index)=>`// Reading fixture ${index}\n`).join(''));
    await page.waitForResponse(response=>response.url().endsWith('/api/workspace')&&response.ok());
    await page.getByRole('tab',{name:'测试',exact:true}).click();
    await expect(page.getByText('Added browser test',{exact:true})).toBeVisible();
    await page.getByRole('button',{name:'查看测试源码',exact:true}).click();
    await expect(page.getByRole('dialog')).toContainText('browser-added-test');
    await page.keyboard.press('Escape');
    await page.getByRole('tab',{name:'实现',exact:true}).click();
    await page.getByRole('button',{name:'src/demo.ts',exact:true}).click();
    const source=page.getByLabel('源码原文',{exact:true});
    await source.fill('export const demo = 2;\n');
    await expect.poll(()=>readFileSync(join(root,'src/demo.ts'),'utf8')).toBe('export const demo = 2;\n');
    await sidebar.getByRole('link',{name:'Git 变更',exact:true}).click();
    await expect(page.getByRole('tab',{name:/Docs 变更/})).toHaveAttribute('aria-selected','true');
    await expect(page.getByRole('region',{name:'新增测试用例',exact:true})).toHaveCount(0);
    await page.getByRole('tab',{name:/测试用例变更/}).click();
    await expect(gitTree).toContainText('Added browser test');
    await expect(gitTree).not.toContainText('src/demo.ts');
    await gitTree.getByRole('button').filter({hasText:'Added browser test'}).click();
    await expect(page.locator('[data-git-diff]')).toContainText('browser-added-test');
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await expect(page).toHaveURL(/line=4/);
    await expect(page.locator('[data-git-diff] #git-line-4')).toBeVisible();
    const diffScroll = page.getByTestId('git-diff-scroll');
    await diffScroll.evaluate(element => { element.scrollTop = 250; });
    await expect.poll(() => diffScroll.evaluate(element => element.scrollTop)).toBe(250);
    await page.getByRole('tab',{name:/Docs 变更/}).click();
    await gitTree.getByRole('button',{name:'docs/feature/browser-feature/README.md',exact:true}).click();
    await page.getByRole('tab',{name:/测试用例变更/}).click();
    await expect(gitTree.getByRole('button',{name:'test/demo.test.ts',exact:true})).toHaveAttribute('aria-current','page');
    await expect.poll(() => diffScroll.evaluate(element => element.scrollTop)).toBe(250);
    await page.getByRole('tab',{name:/Docs 变更/}).click();
    await expect(gitTree.getByRole('button',{name:'docs/feature/browser-feature/README.md',exact:true})).toHaveAttribute('aria-current','page');
    await page.getByRole('tab',{name:/测试用例变更/}).click();
    await page.reload();
    await expect(page.locator('[data-git-diff]')).toContainText('browser-added-test');
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await expect(page.getByRole('tab',{name:/测试用例变更/})).toHaveAttribute('aria-selected','true');
    await expect(sidebar.getByRole('link',{name:'测试',exact:true})).toHaveCount(0);
    await expect(sidebar.getByRole('link',{name:'实现',exact:true})).toHaveCount(0);
    await page.setViewportSize({width:390,height:844});
    await page.getByRole('button',{name:'变更文件',exact:true}).click();
    await expect(page.getByRole('dialog')).toContainText('test');
    await gitTree.getByRole('button',{name:'test/demo.test.ts',exact:true}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await expect(page.locator('[data-git-diff]')).toContainText('browser-added-test');
    await page.getByRole('button',{name:'Toggle Sidebar',exact:true}).click();
    await expect(page.getByRole('link',{name:'Feature',exact:true})).toBeVisible();
    await page.getByRole('link',{name:'Feature',exact:true}).click();
    await expect(page.locator('[data-mobile="true"]')).toHaveCount(0);
    await page.getByRole('button',{name:'内容导航',exact:true}).click();
    await navigation.getByRole('link',{name:'Browser authoring',exact:true}).click();
    await nestedCase.click();
    await expect(page.getByRole('heading',{name:'Nested browser flow',exact:true}).first()).toBeVisible();
    await expect(page.locator('[data-mobile="true"]')).toHaveCount(0);
    assert.deepEqual(errors,[]);
  } finally {await browser?.close();await server?.close();rmSync(root,{recursive:true,force:true});}
});
