import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { appendFileSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync, renameSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import { chromium, expect, type Browser } from '@playwright/test';
import { initialize, LocalRepository } from '../dist/storage.js';
import { startViewServer, type ViewServerHandle } from '../dist/view-server.js';
import { createDocument } from '../dist/documents.js';

// @use-case docs/feature/web-workbench/use-case/use-web-workbench.md
test('the docs sidebar renders and edits constitution body through an explicit revision', async () => {
  const root = mkdtempSync(join(tmpdir(), 'concord-project-docs-'));
  let server: ViewServerHandle | undefined;
  let browser: Browser | undefined;
  try {
    execFileSync('git', ['init', '-q', root]);
    const repo = new LocalRepository(root, { initialize: true });
    try {
      initialize(repo, false, { testRoots: [] });
      createDocument(repo, 'design', { id: 'history', title: 'Historical Design', alternatives: ['local'] });
    } finally { repo.close(); }
    renameSync(join(root, 'docs/design/history'), join(root, 'memory/history'));
    appendFileSync(join(root, 'docs/architecture.md'), '\n[Constitution clause](constitution.md#c-example)\n');
    appendFileSync(join(root, 'docs/constitution.md'), `\n[Jump to principle](#c-example)\n${'\nSpacer paragraph.\n'.repeat(90)}\n<a id="c-example"></a>\n## Example principle\n\n<script>window.concordInjected = true</script>\n\n<img src="invalid-image" onerror="window.concordInjected = true" />\n`);
    const constitution = readFileSync(join(root, 'docs/constitution.md'), 'utf8');
    mkdirSync(join(root, 'docs/_template/design-decision/plans/example'), { recursive: true });
    writeFileSync(join(root, 'docs/_template/design-decision/plans/example/architecture.md'), '# Nested architecture\n\nTemplate body.\n');
    server = await startViewServer({ root, host: '127.0.0.1', port: 0 });
    const executablePath = process.env.CONCORD_BROWSER_PATH ?? (existsSync('/run/current-system/sw/bin/chromium') ? '/run/current-system/sw/bin/chromium' : undefined);
    browser = await chromium.launch({ headless: true, ...(executablePath ? { executablePath } : {}), args: ['--no-sandbox'] });
    const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
    const errors: string[] = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(`http://127.0.0.1:${server.port}/`);
    await page.getByRole('link', { name: '文档', exact: true }).click();
    const preview = page.getByTestId('project-doc-preview');
    await expect(preview.getByRole('heading', { name: 'Project documentation' })).toBeVisible();
    await page.locator('a[href="/docs?file=memory%2Fhistory%2FREADME.md"]').click();
    await expect(preview).toContainText('Historical contract');
    await expect(preview.locator('[contenteditable="true"]')).toHaveCount(0);
    assert.match(readFileSync(join(root, 'memory/history/README.md'), 'utf8'), /kind: design/u);
    await page.goto(`http://127.0.0.1:${server.port}/docs`);
    await expect(preview.getByRole('heading', { name: 'Project documentation' })).toBeVisible();
    await expect(preview).toContainText('Where facts belong');
    await preview.getByRole('link', { name: 'Architecture', exact: true }).click();
    await expect(preview).toContainText('Components and responsibilities');
    assert.equal(new URL(page.url()).searchParams.get('file'), 'docs/architecture.md');
    await preview.getByRole('link', { name: 'Constitution clause' }).click();
    await expect(preview.getByRole('heading', { name: 'Example principle' })).toBeInViewport();
    assert.equal(new URL(page.url()).searchParams.get('file'), 'docs/constitution.md');
    assert.equal(new URL(page.url()).hash, '#c-example');
    const navigation = page.getByRole('navigation', { name: '内容导航' });
    await navigation.getByRole('link', { name: 'Project constitution', exact: true }).click();
    const rendered = preview.getByTestId('markdown-preview');
    await expect(rendered.getByText('No project principles have been adopted.')).toBeVisible();
    await expect(preview.locator('.callout--warning')).toHaveCount(0);
    await expect(preview.locator('[contenteditable="true"]')).toHaveCount(0);
    await expect(preview.getByRole('heading', { name: 'Example principle' })).toBeVisible();
    await expect(preview.getByText('已切换为原文编辑')).toHaveCount(0);
    await expect(preview.locator('textarea')).toHaveCount(0);
    await expect(preview.locator('#user-content-c-example')).toHaveCount(1);
    await expect(preview.locator('script, [onerror]')).toHaveCount(0);
    assert.equal(await page.evaluate(() => 'concordInjected' in window), false);
    await preview.getByRole('link', { name: 'Jump to principle' }).click();
    await expect(preview.getByRole('heading', { name: 'Example principle' })).toBeInViewport();
    assert.equal(new URL(page.url()).hash, '#c-example');
    await page.reload();
    await expect(preview.getByRole('heading', { name: 'Example principle' })).toBeInViewport();
    assert.equal(readFileSync(join(root, 'docs/constitution.md'), 'utf8'), constitution);
    await page.getByRole('button', { name: '编辑宪法' }).click();
    await expect(preview.getByLabel('宪法正文')).toHaveValue(/Example principle/u);
    await preview.getByLabel('修订原因').fill('Adopt the project principles');
    await preview.getByLabel('修订影响').fill('Future project changes');
    await preview.getByLabel('修订来源').fill('docs/architecture.md');
    assert.equal(readFileSync(join(root, 'docs/constitution.md'), 'utf8'), constitution);
    await page.getByRole('button', { name: '采用宪法' }).click();
    await expect(page.getByRole('status').filter({ hasText: '阅读中' })).toBeVisible();
    const adopted = readFileSync(join(root, 'docs/constitution.md'), 'utf8');
    assert.match(adopted, /status: active/u);
    assert.match(adopted, /reason: Adopt the project principles/u);
    assert.match(adopted, /impact: Future project changes/u);
    assert.match(adopted, /docs\/architecture\.md/u);
    assert.match(adopted, /<a id="c-example"><\/a>/u);
    await page.getByRole('button', { name: '编辑宪法' }).click();
    await preview.getByLabel('宪法正文').fill(`${await preview.getByLabel('宪法正文').inputValue()}\nBrowser amendment.\n`);
    await preview.getByLabel('修订原因').fill('Clarify a principle');
    await preview.getByLabel('修订影响').fill('Readers of this constitution');
    await expect(preview.getByLabel('修订来源')).toBeEmpty();
    await navigation.getByRole('link', { name: 'Project architecture', exact: true }).click();
    await expect(page.getByRole('dialog', { name: '离开并丢弃未保存内容？' })).toBeVisible();
    assert.equal(new URL(page.url()).searchParams.get('file'), 'docs/constitution.md');
    await page.getByRole('button', { name: '留在此页' }).click();
    appendFileSync(join(root, 'docs/constitution.md'), '\nExternal note.\n');
    await page.getByRole('button', { name: '保存修订' }).click();
    await expect(page.getByRole('dialog', { name: '比较宪法草稿' })).toBeVisible();
    await expect(preview.getByLabel('宪法正文')).toHaveValue(/Browser amendment/u);
    assert.doesNotMatch(readFileSync(join(root, 'docs/constitution.md'), 'utf8'), /Browser amendment/u);
    await page.getByRole('button', { name: '丢弃草稿并载入' }).click();
    await preview.getByLabel('宪法正文').fill(`${await preview.getByLabel('宪法正文').inputValue()}\nBrowser amendment.\n`);
    await preview.getByLabel('修订原因').fill('Clarify a principle');
    await preview.getByLabel('修订影响').fill('Readers of this constitution');
    await expect(preview.getByLabel('修订来源')).toBeEmpty();
    await page.getByRole('button', { name: '保存修订' }).click();
    await expect(page.getByRole('status').filter({ hasText: '阅读中' })).toBeVisible();
    const amended = readFileSync(join(root, 'docs/constitution.md'), 'utf8');
    assert.match(amended, /Browser amendment/u);
    assert.match(amended, /External note/u);
    assert.match(amended, /reason: Adopt the project principles/u);
    assert.match(amended, /reason: Clarify a principle/u);
    assert.match(amended, /reason: Clarify a principle\n\s+sources: \[\]/u);
    await page.getByRole('button', { name: '编辑宪法' }).click();
    await preview.getByLabel('宪法正文').fill(`${await preview.getByLabel('宪法正文').inputValue()}\nDelayed amendment.\n`);
    await preview.getByLabel('修订原因').fill('Delayed save');
    await preview.getByLabel('修订影响').fill('Navigation after the save');
    let releaseAction: () => void = () => undefined;
    const heldAction = new Promise<void>(resolve => { releaseAction = resolve; });
    let actionStarted: () => void = () => undefined;
    const actionObserved = new Promise<void>(resolve => { actionStarted = resolve; });
    await page.route('**/api/action', async route => {
      if (route.request().postDataJSON()?.action !== 'constitution.amend') return route.continue();
      actionStarted();
      await heldAction;
      await route.continue();
    });
    await page.getByRole('button', { name: '保存修订' }).click();
    await actionObserved;
    await expect(page.getByRole('status').filter({ hasText: '正在保存…' })).toBeVisible();
    await navigation.getByRole('link', { name: 'Project architecture', exact: true }).click();
    await page.waitForTimeout(100);
    assert.equal(new URL(page.url()).searchParams.get('file'), 'docs/constitution.md');
    await expect(page.getByRole('dialog', { name: '离开并丢弃未保存内容？' })).toHaveCount(0);
    assert.doesNotMatch(readFileSync(join(root, 'docs/constitution.md'), 'utf8'), /Delayed amendment/u);
    releaseAction();
    await expect(page).toHaveURL(/file=docs%2Farchitecture\.md/u);
    assert.match(readFileSync(join(root, 'docs/constitution.md'), 'utf8'), /Delayed amendment/u);
    await page.unroute('**/api/action');
    const templates = navigation.getByRole('list', { name: '参考模板' });
    await templates.getByRole('button', { name: 'design-decision', exact: true }).focus();
    await page.keyboard.press('Enter');
    await expect(templates.getByRole('button', { name: 'design-decision', exact: true })).toHaveAttribute('aria-expanded', 'true');
    await page.getByLabel('筛选文档').fill('plans/example/architecture');
    await templates.getByRole('link', { name: 'architecture.md', exact: true }).click();
    await expect(preview.getByRole('heading', { name: 'Nested architecture' })).toBeVisible();
    await page.getByLabel('筛选文档').fill('');
    await expect(templates.locator('a[aria-current="page"]')).toHaveText('architecture.md');
    await page.reload();
    await expect(templates.locator('a[aria-current="page"]')).toBeVisible();
    await page.setViewportSize({ width: 390, height: 844 });
    await page.getByRole('button', { name: '内容导航', exact: true }).click();
    await expect(page.getByRole('dialog').getByRole('link', { name: 'Project architecture', exact: true })).toBeVisible();
    const currentConstitution = readFileSync(join(root, 'docs/constitution.md'), 'utf8');
    writeFileSync(join(root, 'docs/constitution.md'), currentConstitution.replace('format: concord.constitution/v1\n', 'format: concord.constitution/v1\nunknownField: true\n'));
    await page.getByRole('dialog').getByRole('link', { name: 'Project constitution', exact: true }).click();
    await expect(preview.getByText('宪法 frontmatter 无法识别，不能在此编辑。')).toBeVisible();
    await expect(page.getByRole('button', { name: '编辑宪法' })).toHaveCount(0);
    const legacy = currentConstitution
      .replace('format: concord.constitution/v1\n', 'format: concord.constitution/v1\nversion: 1.0.0\n')
      .replace(/^  - date:/gmu, '  - version: 1.0.0\n    date:');
    writeFileSync(join(root, 'docs/constitution.md'), legacy);
    await page.reload();
    await expect(page.getByRole('button', { name: '编辑宪法' })).toBeVisible();
    writeFileSync(join(root, 'docs/constitution.md'), legacy.replace('format: concord.constitution/v1\n', 'format: concord.constitution/v1\nunknownField: true\n'));
    await page.reload();
    await expect(preview.getByText('宪法 frontmatter 无法识别，不能在此编辑。')).toBeVisible();
    await expect(page.getByRole('button', { name: '编辑宪法' })).toHaveCount(0);
    assert.equal(errors.join('\n'), '');
  } finally {
    await browser?.close();
    await server?.close();
    rmSync(root, { recursive: true, force: true });
  }
});
