import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import { chromium, expect, type Browser } from '@playwright/test';
import { addPage, createDocument } from '../dist/documents.js';
import { initialize, LocalRepository } from '../dist/storage.js';
import { startViewServer, type ViewServerHandle } from '../dist/view-server.js';
import { projectConfigPath, readProjectConfig, writeProjectConfig } from './support.js';

// @use-case docs/feature/web-workbench/use-case/use-web-workbench.md
test('browser opens and refreshes a deep link without credentials and retries initial load failures', async () => {
  const root = mkdtempSync(join(tmpdir(), 'concord-browser-open-'));
  let server: ViewServerHandle | undefined;
  let browser: Browser | undefined;
  try {
    execFileSync('git', ['init', '-q', root]);
    const repo = new LocalRepository(root, { initialize: true });
    try {
      initialize(repo, false, { testRoots: [] });
      createDocument(repo, 'feature', { id: 'web', title: 'Direct access fixture' });
      createDocument(repo, 'use-case', { id: 'floating-path', title: 'Floating user path', feature: 'web' });
      createDocument(repo, 'engineering', { id: 'floating-tooling', title: 'Floating tooling' });
      createDocument(repo, 'roadmap', { id: 'planned', title: 'Planned direction' });
      createDocument(repo, 'feature', {
        id: 'html',
        title: 'Raw HTML fixture',
        body: '# Raw HTML fixture\n\n<details><summary>More</summary>\n\nContent\n\n</details>\n',
      });
      for (let index = 0; index < 24; index += 1) createDocument(repo, 'feature', { id: `fixture-${index}`, title: `Navigation fixture ${index}` });
    } finally { repo.close(); }
    writeFileSync(join(root, 'docs/concepts.json'), JSON.stringify({ format: 'concord.concepts/v1', concepts: [{ id: 'direct-access', definition: '浏览器直接打开工作台', names: { zh: { preferred: '直接访问', aliases: ['直接打开'], deprecated: ['旧访问'] }, en: { preferred: 'Direct access', aliases: ['Open directly'] } } }] }));
    writeFileSync(join(root, 'docs/feature/web/concepts.json'), JSON.stringify({ format: 'concord.concepts/v1', concepts: [{ id: 'workbench', definition: 'Web Feature 所属定义', names: { en: { preferred: 'Workbench' } } }] }));
    writeFileSync(join(root, 'docs/feature/html/concepts.json'), JSON.stringify({ format: 'concord.concepts/v1', concepts: [{ id: 'html-only', definition: '相邻 Feature 定义', names: { en: { preferred: 'HTML Only' } } }] }));
    server = await startViewServer({ root, host: '127.0.0.1', port: 0 });
    const executablePath = process.env.CONCORD_BROWSER_PATH ?? (existsSync('/run/current-system/sw/bin/chromium') ? '/run/current-system/sw/bin/chromium' : undefined);
    browser = await chromium.launch({ headless: true, ...(executablePath ? { executablePath } : {}), args: ['--no-sandbox'] });
    const page = await browser.newPage();
    const authorizations: (string | undefined)[] = [];
    const errors: string[] = [];
    page.on('request', request => {
      if (new URL(request.url()).pathname.startsWith('/api/')) authorizations.push(request.headers().authorization);
    });
    page.on('pageerror', error => errors.push(error.message));
    await page.route('**/api/workspace', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ ok: false, error: 'FixtureUnavailable', message: '工作区暂时不可用' }) }));
    const url = `http://127.0.0.1:${server.port}/features/web`;
    await page.goto(url);
    await expect(page.getByRole('alert')).toHaveText('工作区暂时不可用');
    await expect(page.getByLabel('访问密钥', { exact: true })).toHaveCount(0);
    await page.unroute('**/api/workspace');
    await page.getByRole('button', { name: '重试', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Direct access fixture', exact: true })).toBeVisible();
    await expect(page).toHaveURL(url);
    await page.getByRole('link', { name: '总览', exact: true }).click();
    const floating = page.getByText('悬空功能', { exact: true }).locator('xpath=ancestor::*[@data-slot="card"]');
    await expect(floating.getByRole('link', { name: /Direct access fixture/ })).toBeVisible();
    await expect(floating.getByRole('link', { name: /Floating user path/ })).toBeVisible();
    await expect(floating.getByRole('link', { name: /Floating tooling/ })).toBeVisible();
    await page.context().grantPermissions(['clipboard-read', 'clipboard-write'], { origin: `http://127.0.0.1:${server.port}` });
    await floating.getByRole('button', { name: '复制全部', exact: true }).click();
    await expect(page.getByText(/已复制 \d+ 项悬空功能。/)).toBeVisible();
    const copied = await page.evaluate(() => navigator.clipboard.readText());
    assert.match(copied, /- \[Feature\] Direct access fixture — docs\/feature\/web\/README\.md/);
    assert.match(copied, /- \[Use Case\] Floating user path — docs\/feature\/web\/use-case\/floating-path\.md/);
    assert.match(copied, /- \[Engineering\] Floating tooling — docs\/engineering\/floating-tooling\/README\.md/);
    await page.evaluate(() => {
      Object.defineProperty(navigator, 'clipboard', { configurable: true, value: undefined });
      (window as typeof window & { copiedFallback?: string }).copiedFallback = '';
      document.execCommand = command => {
        if (command !== 'copy') return false;
        (window as typeof window & { copiedFallback?: string }).copiedFallback = (document.activeElement as HTMLTextAreaElement | null)?.value ?? '';
        return true;
      };
    });
    await floating.getByRole('button', { name: '复制全部', exact: true }).click();
    assert.match(await page.evaluate(() => (window as typeof window & { copiedFallback?: string }).copiedFallback ?? ''), /Floating tooling/);
    await floating.getByRole('link', { name: /Floating user path/ }).click();
    await expect(page.getByRole('heading', { name: 'Floating user path', exact: true }).first()).toBeVisible();
    await page.getByRole('tab', { name: '术语', exact: true }).click();
    await expect(page.getByText('docs/feature/web/use-case/concepts.json', { exact: true })).toBeVisible();
    await expect(page.getByText('docs/concepts.json#direct-access', { exact: true })).toBeVisible();
    await expect(page.getByText('docs/feature/web/concepts.json#workbench', { exact: true })).toBeVisible();
    await expect(page.getByText('docs/feature/html/concepts.json#html-only', { exact: true })).toHaveCount(0);
    await page.goto(url);
    const contentNavigation = page.getByRole('navigation', { name: '内容导航', exact: true });
    assert.equal(await contentNavigation.evaluate(element => element.parentElement!.scrollHeight > element.parentElement!.clientHeight), true);
    assert.equal(await contentNavigation.evaluate(element => getComputedStyle(element.parentElement!).scrollbarWidth), 'none');
    const pagePane = page.locator('.document-workspace > .page');
    await contentNavigation.evaluate(element => { element.parentElement!.scrollTop = 160; });
    assert.equal(await contentNavigation.evaluate(element => element.parentElement!.scrollTop), 160);
    assert.equal(await pagePane.evaluate(element => element.scrollTop), 0);
    const themeToggle = page.getByRole('button', { name: '切换至深色主题', exact: true });
    await expect(themeToggle).toBeVisible();
    await themeToggle.click();
    await expect(page.locator('html')).toHaveClass(/dark/);
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
    assert.equal(await page.evaluate(() => localStorage.getItem('concord-theme')), 'dark');
    await page.reload();
    await expect(page.getByRole('heading', { name: 'Direct access fixture', exact: true })).toBeVisible();
    await expect(page).toHaveURL(url);
    await expect(page.locator('html')).toHaveClass(/dark/);
    await expect(page.getByRole('button', { name: '切换至浅色主题', exact: true })).toBeVisible();
    await expect(page.getByTestId('document-header').getByRole('button', { name: '重新载入', exact: true })).toBeVisible();
    await page.getByRole('tab', { name: '术语', exact: true }).click();
    await expect(page.getByText('docs/concepts.json#direct-access', { exact: true })).toBeVisible();
    await expect(page.getByText('docs/feature/web/concepts.json#workbench', { exact: true })).toBeVisible();
    await expect(page.getByText(/zh · 首选：直接访问/u)).toBeVisible();
    await expect(page.getByText(/en · 首选：Direct access/u)).toBeVisible();
    await expect(page.getByText(/允许名称：直接打开；弃用名称：旧访问/u)).toBeVisible();
    await expect(page.getByText('浏览器直接打开工作台', { exact: true })).toBeVisible();
    await expect(page.getByRole('link', { name: '打开术语' })).toHaveAttribute('href', '/terms');
    await expect(page.getByText('docs/feature/html/concepts.json#html-only', { exact: true })).toHaveCount(0);
    assert.equal(new URL(page.url()).searchParams.get('tab'), 'terminology');
    await page.getByRole('tab', { name: '实现', exact: true }).click();
    await expect(page.getByRole('tab', { name: '实现', exact: true })).toHaveAttribute('data-state', 'active');
    await page.goBack();
    await expect(page.getByRole('tab', { name: '术语', exact: true })).toHaveAttribute('data-state', 'active');
    await page.goForward();
    await expect(page.getByRole('tab', { name: '实现', exact: true })).toHaveAttribute('data-state', 'active');
    await page.reload();
    await expect(page.getByRole('tab', { name: '实现', exact: true })).toHaveAttribute('data-state', 'active');
    await expect(page.getByRole('tab', { name: '关系', exact: true })).toHaveCount(0);
    await expect(page.getByRole('tab', { name: '生命周期', exact: true })).toHaveCount(0);
    await expect(page.getByTestId('document-header').getByRole('button', { name: '新建 Feature', exact: true })).toHaveCount(0);
    await expect(contentNavigation.getByRole('button', { name: '新建 Feature', exact: true })).toBeVisible();
    await page.goto(`${url}?tab=actions`);
    await expect(page.getByRole('tab', { name: '元数据', exact: true })).toHaveAttribute('data-state', 'active');
    await expect(page.getByText('创建于', { exact: true })).toBeVisible();
    await page.getByLabel('文档标题', { exact: true }).fill('Direct access renamed');
    await page.getByRole('tab', { name: 'Use Cases', exact: true }).click();
    await expect(contentNavigation.getByRole('link', { name: 'Direct access renamed', exact: true })).toBeVisible();
    await page.getByRole('tab', { name: '正文', exact: true }).click();
    await expect(page.locator('.editor-shell > .editor-shell__bar')).toHaveCount(0);
    await contentNavigation.getByRole('link', { name: 'Raw HTML fixture', exact: true }).click();
    await expect(page.getByText('已切换为原文编辑', { exact: true })).toBeVisible();
    await expect(page.getByLabel('Markdown 原文', { exact: true })).toContainText('<details>');
    await page.goto(`http://127.0.0.1:${server.port}/roadmap/planned?tab=actions`);
    await expect(page.getByRole('tab', { name: '生命周期', exact: true })).toHaveAttribute('data-state', 'active');
    await page.getByLabel('采用为 Feature ID', { exact: true }).fill('adopted-direction');
    await page.getByRole('button', { name: '采用 Roadmap', exact: true }).click();
    await expect(page.getByText('adopted', { exact: true })).toBeVisible();
    await expect(page.getByRole('heading', { name: '可用操作', exact: true })).toHaveCount(0);
    await expect(page.getByText('Unexpected Application Error!', { exact: true })).toHaveCount(0);
    const configurationPath = join(root, 'concord.config.ts');
    const originalConfiguration = readFileSync(configurationPath, 'utf8');
    const invalidConfiguration = 'export default { broken: ; }';
    writeFileSync(configurationPath, invalidConfiguration);
    await page.goto(`http://127.0.0.1:${server.port}/settings`);
    await expect(page.getByRole('heading', { name: '项目配置无法读取', exact: true })).toBeVisible();
    await expect(page.getByLabel('无效配置原文', { exact: true })).toHaveValue(invalidConfiguration);
    await expect(page.getByLabel('无效配置原文', { exact: true })).not.toBeEditable();
    await expect(page.getByRole('button', { name: '初始化', exact: true })).toHaveCount(0);
    assert.equal(readFileSync(configurationPath, 'utf8'), invalidConfiguration);
    writeFileSync(configurationPath, originalConfiguration);
    await page.getByRole('button', { name: '重新载入', exact: true }).click();
    await expect(page.getByLabel('Project ID', { exact: true })).toBeVisible();
    assert.ok(authorizations.length > 0);
    assert.ok(authorizations.every(value => value === undefined));
    assert.deepEqual(errors, []);
  } finally {
    await browser?.close();
    await server?.close();
    rmSync(root, { recursive: true, force: true });
  }
});

// @use-case docs/feature/documentation-quality/use-case/manage-scoped-terminology.md
test('terminology tab discards a previous document response and shows scoped JSON diagnostics', async () => {
  const root = mkdtempSync(join(tmpdir(), 'concord-terminology-browser-'));
  let server: ViewServerHandle | undefined;
  let browser: Browser | undefined;
  try {
    execFileSync('git', ['init', '-q', root]);
    const repo = new LocalRepository(root, { initialize: true });
    try {
      initialize(repo, false, { testRoots: [] });
      createDocument(repo, 'feature', { id: 'alpha', title: 'Alpha Feature' });
      createDocument(repo, 'feature', { id: 'beta', title: 'Beta Feature' });
    } finally { repo.close(); }
    writeFileSync(join(root, 'docs/concepts.json'), JSON.stringify({ format: 'concord.concepts/v1', concepts: [{ id: 'shared', definition: 'Shared definition', names: { en: { preferred: 'Shared' } } }] }));
    writeFileSync(join(root, 'docs/feature/alpha/concepts.json'), JSON.stringify({ format: 'concord.concepts/v1', concepts: [{ id: 'alpha', definition: 'Alpha definition', names: { en: { preferred: 'Alpha' } } }] }));
    writeFileSync(join(root, 'docs/feature/beta/concepts.json'), JSON.stringify({ format: 'concord.concepts/v1', concepts: [{ id: 'beta', definition: 'Beta definition', names: { en: { preferred: 'Beta' } } }], imports: ['docs/concepts.json#missing'] }));
    server = await startViewServer({ root, host: '127.0.0.1', port: 0 });
    const executablePath = process.env.CONCORD_BROWSER_PATH ?? (existsSync('/run/current-system/sw/bin/chromium') ? '/run/current-system/sw/bin/chromium' : undefined);
    browser = await chromium.launch({ headless: true, ...(executablePath ? { executablePath } : {}), args: ['--no-sandbox'] });
    const page = await browser.newPage();
    let legacyReads = 0;
    page.on('request', request => { if (request.url().includes('/api/file') && request.url().includes('concepts.md')) legacyReads++; });
    let releaseAlpha!: () => void;
    let interceptedAlpha!: () => void;
    const heldAlpha = new Promise<void>(resolve => { interceptedAlpha = resolve; });
    const release = new Promise<void>(resolve => { releaseAlpha = resolve; });
    await page.route('**/api/action', async route => {
      const input = route.request().postDataJSON() as { action?: string; path?: string };
      if (input.action === 'concepts.show' && input.path === 'docs/feature/alpha/concepts.json') {
        interceptedAlpha();
        await release;
      }
      await route.continue();
    });
    await page.goto(`http://127.0.0.1:${server.port}/features/alpha?tab=terminology`);
    await heldAlpha;
    const navigation = page.getByRole('navigation', { name: '内容导航', exact: true });
    await navigation.getByRole('link', { name: 'Beta Feature', exact: true }).click();
    await page.getByRole('tab', { name: '术语', exact: true }).click();
    await expect(page.getByText('docs/concepts.json#shared', { exact: true })).toBeVisible();
    await expect(page.getByText('docs/feature/beta/concepts.json#beta', { exact: true })).toBeVisible();
    await expect(page.getByText(/DanglingConceptImport/u)).toBeVisible();
    const oldResponse = page.waitForResponse(response => response.url().endsWith('/api/action') && (response.request().postDataJSON() as { action?: string; path?: string }).path === 'docs/feature/alpha/concepts.json');
    releaseAlpha();
    await oldResponse;
    await expect(page.getByText('docs/feature/alpha/concepts.json#alpha', { exact: true })).toHaveCount(0);
    await expect(page.getByText('docs/feature/beta/concepts.json#beta', { exact: true })).toBeVisible();
    assert.equal(legacyReads, 0);
  } finally { await browser?.close(); await server?.close(); rmSync(root, { recursive: true, force: true }); }
});

// @use-case docs/feature/web-workbench/use-case/use-web-workbench.md
test('real browser creates a Feature, edits Markdown, preserves conflicts and opens Git changes', async () => {
  const root=mkdtempSync(join(tmpdir(),'concord-browser-'));
  let server: ViewServerHandle|undefined;
  let browser: Browser|undefined;
  try {
    execFileSync('git',['init','-q',root]);
    const repo=new LocalRepository(root,{initialize:true});
    try {
      initialize(repo,false,{testRoots:['test'],sourceRoots:['src']});
      createDocument(repo,'engineering',{id:'build',title:'Build workflow'});
      const engineeringPath=join(root,'docs/engineering/build/README.md');
      writeFileSync(engineeringPath,`${readFileSync(engineeringPath,'utf8')}\n\`\`\`mermaid\nflowchart LR\n  Source --> Result\n\`\`\`\n`);
      addPage(repo,'engineering','build','architecture');
      writeFileSync(join(root,'docs/engineering/build/architecture.md'),'# Architecture\n\n## Source\n');
      createDocument(repo,'roadmap',{id:'future',title:'Future direction',pages:['architecture']});
      createDocument(repo,'design',{id:'options',title:'Design options',alternatives:['first','second'],pages:['architecture']});
      createDocument(repo,'research',{id:'study',title:'Research study',observedAt:'2026-09-14',sources:['Local observations']});
    } finally {repo.close();}
    mkdirSync(join(root,'src'));
    writeFileSync(join(root,'src/demo.ts'),'// @concord-code\n// @concord-implements docs/engineering/build/architecture.md#source\nexport function demo() { return 1; }\n');
    server=await startViewServer({root,host:'127.0.0.1',port:0});
    const executablePath=process.env.CONCORD_BROWSER_PATH ?? (existsSync('/run/current-system/sw/bin/chromium')?'/run/current-system/sw/bin/chromium':undefined);
    browser=await chromium.launch({headless:true,...(executablePath?{executablePath}:{}),args:['--no-sandbox']});
    const page=await browser.newPage({viewport:{width:1440,height:1000}});
    const errors:string[]=[];
    page.on('pageerror',error=>errors.push(error.message));
    await page.goto(`http://127.0.0.1:${server.port}/features`);
    await expect(page.getByRole('heading',{name:'Feature',exact:true})).toBeVisible();
    assert.equal(await page.getByRole('link',{name:'Feature',exact:true}).evaluate(element=>getComputedStyle(element).display),'flex','sidebar must forward shadcn classes to its links');
    assert.equal(await page.locator('[data-slot="sidebar"]').getByRole('link',{name:'Use Case',exact:true}).count(),0);
    const sidebar=page.locator('[data-slot="sidebar"]');
    const navigation=page.getByRole('navigation',{name:'内容导航',exact:true});
    for (const [category,title,section] of [['Engineering','Build workflow','engineering'],['Roadmap','Future direction','roadmap'],['Design','Design options','design'],['Research','Research study','research']] as const) {
      await sidebar.getByRole('link',{name:category,exact:true}).click();
      const list=navigation.getByRole('list',{name:`${category} 列表`,exact:true});
      await expect(sidebar.getByRole('link',{name:title,exact:true})).toHaveCount(0);
      await list.getByRole('link',{name:title,exact:true}).click();
      await expect(page).toHaveURL(new RegExp(`/${section}/`));
      await expect(list.getByRole('link',{name:title,exact:true})).toHaveAttribute('aria-current','page');
      if (category === 'Roadmap') {
        await expect(page.getByRole('tab', { name: '术语', exact: true })).toBeVisible();
        await expect(page.getByRole('tab', { name: '实现', exact: true })).toHaveCount(0);
        await expect(page.getByRole('tab', { name: '测试', exact: true })).toHaveCount(0);
      }
      if (category === 'Engineering') {
        const diagram=page.getByLabel('Mermaid 图表预览').locator('svg');
        await expect(diagram).toBeVisible();
        const initialDiagram=await diagram.evaluate(element=>element.outerHTML);
        await page.locator('.theme-toggle').click();
        await expect.poll(()=>diagram.evaluate(element=>element.outerHTML)).not.toBe(initialDiagram);
        await page.getByRole('tab',{name:'实现',exact:true}).click();
        await expect(page.getByRole('tab',{name:'实现',exact:true})).toHaveAttribute('data-state','active');
        await expect(page.getByRole('tab',{name:'测试',exact:true})).toHaveCount(0);
        await expect(page.getByText('docs/engineering/build/architecture.md#source',{exact:true})).toBeVisible();
        const implementationRecord=page.locator('.implementation-record').first();
        const columns=await implementationRecord.evaluate(element=>Array.from(element.children).map(child=>child.getBoundingClientRect()));
        assert.ok(columns[1]!.left > columns[0]!.right,'desktop implementation details should occupy the right column');
        assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth <= window.innerWidth),'desktop implementation must not overflow');
        await page.getByRole('button',{name:/src\/demo\.ts/}).click();
        await expect(page.getByRole('dialog')).toContainText('export function demo()');
        await page.getByRole('button',{name:'Close',exact:true}).click();
        await page.setViewportSize({width:900,height:1000});
        const narrowBounds=await implementationRecord.evaluate(element=>Array.from(element.children).map(child=>({top:child.getBoundingClientRect().top,bottom:child.getBoundingClientRect().bottom})));
        assert.ok(narrowBounds[1]!.top > narrowBounds[0]!.bottom,'narrow content should stack implementation details');
        assert.ok(await implementationRecord.evaluate(element=>element.scrollWidth <= element.clientWidth),'narrow content implementation must not overflow horizontally');
        await page.setViewportSize({width:480,height:1000});
        assert.ok(await implementationRecord.evaluate(element=>element.scrollWidth <= element.clientWidth),'mobile implementation must not overflow horizontally');
        await page.setViewportSize({width:1440,height:1000});
        await page.getByRole('button',{name:'添加关联',exact:true}).click();
        await expect(page.getByLabel('代码声明 ID',{exact:true})).toHaveCount(0);
        await page.getByLabel('实现契约引用',{exact:true}).fill('docs/engineering/build/architecture.md#source');
        await page.getByRole('button',{name:'生成',exact:true}).click();
        await expect(page.getByText(/@concord-implements docs\/engineering\/build\/architecture\.md#source/).first()).toBeVisible();
        await page.getByRole('tab',{name:'正文',exact:true}).click();
      }
      if (category !== 'Research') {
        const supportingPage=page.getByTestId('document-file-tree').getByRole('button',{name:category === 'Design' ? 'plans/first/architecture.md' : 'architecture.md',exact:true});
        await supportingPage.click();
        await expect(page.locator('[contenteditable="true"]').first()).toBeVisible();
      }
      await expect(list.getByRole('link',{name:title,exact:true})).toBeVisible();
    }
    await sidebar.getByRole('link',{name:'Feature',exact:true}).click();
    await page.getByRole('button',{name:'新建 Feature',exact:true}).click();
    await page.getByLabel('Feature ID',{exact:true}).fill('browser-feature');
    await page.getByLabel('Feature 标题',{exact:true}).fill('Browser authoring');
    await page.getByRole('checkbox',{name:'Architecture',exact:true}).check();
    await page.getByRole('checkbox',{name:'Library',exact:true}).check();
    await page.getByLabel('初始正文',{exact:true}).fill('# Browser authoring\n\nOriginal paragraph.\n');
    await page.getByRole('button',{name:'创建',exact:true}).click();
    assert.equal(existsSync(join(root,'docs/feature/browser-feature/cli.md')),false);
    await page.getByRole('link').filter({hasText:'Browser authoring'}).first().click();
    await page.getByRole('button',{name:'新建 Feature',exact:true}).click();
    await page.getByLabel('Feature ID',{exact:true}).fill('alternate-feature');
    await page.getByLabel('Feature 标题',{exact:true}).fill('Alternate Feature');
    await page.getByRole('button',{name:'创建',exact:true}).click();
    const featureList=navigation.getByRole('list',{name:'Feature 列表',exact:true});
    await featureList.getByRole('link',{name:'Alternate Feature',exact:true}).click();
    await expect(page.getByRole('heading',{name:'Alternate Feature',exact:true}).first()).toBeVisible();
    await expect(featureList.getByRole('link',{name:'Browser authoring',exact:true})).toBeVisible();
    await featureList.getByRole('link',{name:'Browser authoring',exact:true}).click();
    await expect(featureList.getByRole('link',{name:'Alternate Feature',exact:true})).toBeVisible();
    await expect(page.locator('.page .card-grid')).toHaveCount(0);
    await navigation.getByLabel('筛选 Feature',{exact:true}).fill('browser-feature');
    await expect(featureList.getByRole('link',{name:'Alternate Feature',exact:true})).toHaveCount(0);
    await navigation.getByLabel('筛选 Feature',{exact:true}).fill('');
    const editor=page.locator('[contenteditable="true"]').first();
    await expect(editor).toBeVisible();
    await expect(page.locator('.page .page-header')).toHaveCount(0);
    await expect(page.locator('.editor-shell__bar .eyebrow')).toHaveCount(0);
    const path=join(root,'docs/feature/browser-feature/README.md');
    const original=readFileSync(path,'utf8');
    await expect(page.getByRole('button',{name:'保存',exact:true})).toHaveCount(0);
    assert.equal(readFileSync(path,'utf8'),original,'loading must not normalize the file');
    let busySaveResponses = 0;
    await page.route('**/api/action', async route => {
      const action = route.request().postDataJSON() as { action?: string };
      if (action.action === 'document.set' && busySaveResponses++ === 0) {
        await route.fulfill({ status: 409, contentType: 'application/json', body: JSON.stringify({ ok: false, error: 'RepositoryBusy', message: 'shared Trace lease is busy' }) });
      } else await route.continue();
    });
    await editor.fill('Browser edited paragraph.');
    await page.getByRole('tab',{name:'术语',exact:true}).click();
    await expect(page.getByRole('tab',{name:'术语',exact:true})).toHaveAttribute('data-state', 'active');
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await page.getByRole('tab',{name:'正文',exact:true}).click();
    await expect(editor).toContainText('Browser edited paragraph.');
    await expect.poll(()=>readFileSync(path,'utf8')).toContain('Browser edited paragraph.');
    assert.ok(busySaveResponses >= 2, 'a transient lease conflict retries the save');
    await page.unroute('**/api/action');
    await page.getByRole('tab',{name:'元数据',exact:true}).click();
    await page.getByLabel('文档标题',{exact:true}).fill('Browser authoring renamed');
    await expect(featureList.getByRole('link',{name:'Browser authoring renamed',exact:true})).toBeVisible();
    await page.getByLabel('文档标题',{exact:true}).fill('Browser authoring');
    await expect(featureList.getByRole('link',{name:'Browser authoring',exact:true})).toBeVisible();
    await page.getByRole('tab',{name:'正文',exact:true}).click();
    await expect(editor).toBeVisible();
    let releaseSave: (() => void) | undefined;
    const holdSave = new Promise<void>(resolve => { releaseSave = resolve; });
    let writes = 0;
    await page.route('**/api/action', async route => {
      const action = route.request().postDataJSON() as { action?: string; path?: string };
      if (action.action === 'document.set' && action.path === 'docs/feature/browser-feature/README.md') {
        writes++;
        if (writes === 1) await holdSave;
      }
      await route.continue();
    });
    await editor.fill('Browser edited paragraph. First revision.');
    await expect.poll(() => writes).toBe(1);
    await editor.fill('Browser edited paragraph. Latest revision.');
    assert.equal(writes, 1, 'later input waits behind the in-flight save');
    releaseSave?.();
    await expect.poll(()=>readFileSync(path,'utf8')).toContain('Latest revision.');
    assert.equal(writes, 2);
    await page.unroute('**/api/action');
    await editor.fill('Unsaved browser draft.');
    const disk=readFileSync(path,'utf8').replace('Browser edited paragraph.','External editor wins.');
    writeFileSync(path,disk);
    await expect(page.getByRole('dialog')).toBeVisible();
    await expect(page.getByRole('dialog')).toContainText('Unsaved browser draft.');
    assert.equal(readFileSync(path,'utf8'),disk,'conflict must preserve the external edit');
    await page.getByRole('button',{name:'丢弃草稿并载入',exact:true}).click();
    await expect(page.getByRole('button',{name:'新建 Use Case',exact:true})).toHaveCount(0);
    await page.getByRole('tab',{name:'Use Cases',exact:true}).click();
    await page.getByRole('button',{name:'新建 Use Case',exact:true}).click();
    await page.getByLabel('Use Case ID',{exact:true}).fill('browser-flow');
    await page.getByLabel('Use Case 标题',{exact:true}).fill('Nested browser flow');
    await page.getByRole('button',{name:'创建',exact:true}).click();
    const nestedCase=page.locator('.feature-use-cases').getByRole('link').filter({hasText:'Nested browser flow'});
    await expect(nestedCase).toBeVisible();
    await expect(sidebar.getByRole('link',{name:'Nested browser flow',exact:true})).toHaveCount(0);
    const primaryBounds=await sidebar.boundingBox();
    const contentBounds=await navigation.boundingBox();
    assert.ok(primaryBounds && contentBounds && contentBounds.x >= primaryBounds.x + primaryBounds.width, 'content navigation occupies its own column');
    assert.match(readFileSync(join(root,'docs/feature/browser-feature/use-case/browser-flow.md'),'utf8'),/feature: docs\/feature\/browser-feature\/README\.md/);
    await page.getByRole('tab',{name:'正文',exact:true}).click();
    await editor.fill('External editor wins. Flushed from Feature.');
    await page.getByRole('tab',{name:'Use Cases',exact:true}).click();
    await expect(page.getByRole('tab',{name:'Use Cases',exact:true})).toHaveAttribute('data-state','active');
    assert.ok(readFileSync(path,'utf8').includes('Flushed from Feature.'));
    await nestedCase.click();
    const drawer=page.getByRole('dialog',{name:'Nested browser flow',exact:true});
    await expect(drawer).toBeVisible();
    await expect(page.locator('.page [inert]')).toContainText('Use Cases');
    await expect(drawer.getByRole('heading',{name:'Nested browser flow',exact:true}).first()).toBeVisible();
    await expect.poll(async () => {
      const bounds=await drawer.boundingBox();
      return bounds ? Math.round(bounds.x + bounds.width) : 0;
    }).toBe(1440);
    await page.goBack();
    await expect(drawer).toHaveCount(0);
    await expect(page.getByRole('tab',{name:'Use Cases',exact:true})).toHaveAttribute('data-state','active');
    assert.equal(new URL(page.url()).searchParams.get('tab'),'use-cases');
    await page.locator('.feature-use-cases').getByRole('link').filter({hasText:'Nested browser flow'}).click();
    const drawerEditor=drawer.locator('[contenteditable="true"]').first();
    await expect(drawerEditor).toBeVisible();
    await drawerEditor.fill('Saved Use Case body.');
    await expect.poll(()=>readFileSync(join(root,'docs/feature/browser-feature/use-case/browser-flow.md'),'utf8')).toContain('Saved Use Case body.');
    await drawerEditor.fill('Saved on drawer close.');
    await drawer.getByRole('button',{name:'Close',exact:true}).click();
    await expect(drawer).toHaveCount(0);
    assert.ok(readFileSync(join(root,'docs/feature/browser-feature/use-case/browser-flow.md'),'utf8').includes('Saved on drawer close.'));
    await nestedCase.click();
    await page.reload();
    await expect(drawer).toBeVisible();
    await expect(drawer.locator('[contenteditable="true"]').first()).toBeVisible();
    await page.getByRole('button',{name:'Close',exact:true}).click();
    await expect(drawer).toHaveCount(0);
    await expect(page.getByRole('tab',{name:'Use Cases',exact:true})).toHaveAttribute('data-state','active');
    await page.getByRole('tab',{name:'正文',exact:true}).click();
    await expect(editor).toContainText('External editor wins.');
    const documentTree=page.getByTestId('document-file-tree');
    await documentTree.getByRole('button',{name:'architecture.md',exact:true}).click();
    await expect(editor).toContainText('Entity Ownership');
    await editor.fill('Architecture from browser.');
    const documentPane=page.locator('.document-workspace > .page');
    await documentPane.evaluate(element=>{element.scrollTop=500;});
    await documentTree.evaluate(element=>{element.scrollTop=80;});
    const treeScrollBefore=await documentTree.evaluate(element=>element.scrollTop);
    await documentTree.getByRole('button',{name:'library.md',exact:true}).click();
    await expect.poll(()=>documentPane.evaluate(element=>element.scrollTop)).toBe(0);
    assert.equal(await documentTree.evaluate(element=>element.scrollTop),treeScrollBefore);
    const outerPage=page.locator('.document-workspace > .page');
    assert.equal(await page.getByTestId('document-file-preview').evaluate(element=>getComputedStyle(element).overflowY),'visible');
    assert.equal(await outerPage.evaluate(element=>getComputedStyle(element).scrollbarWidth),'none');
    assert.equal(await page.getByRole('tablist',{name:'文档详情'}).evaluate(element=>getComputedStyle(element).scrollbarWidth),'none');
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await expect.poll(()=>readFileSync(join(root,'docs/feature/browser-feature/architecture.md'),'utf8')).toContain('Architecture from browser.');
    await expect(page).toHaveURL(/file=docs%2Ffeature%2Fbrowser-feature%2Flibrary.md/);
    await page.goBack();
    await expect(editor).toContainText('Architecture from browser.');
    assert.equal(new URL(page.url()).searchParams.get('file'), 'docs/feature/browser-feature/architecture.md');
    await page.goForward();
    await expect(page).toHaveURL(/file=docs%2Ffeature%2Fbrowser-feature%2Flibrary.md/);
    await page.getByRole('link',{name:'Git 变更',exact:true}).click();
    await expect(page.getByRole('complementary',{name:'Git 变更 侧栏'})).toBeVisible();
    const gitTree = page.getByRole('navigation',{name:'Git 文件树',exact:true});
    await expect(page.getByRole('complementary', {name:'Git 变更 侧栏'}).getByRole('tablist', {name:'变更分类'})).toBeVisible();
    await expect(gitTree.getByRole('button',{name:'docs/feature/browser-feature/README.md',exact:true})).toBeVisible();
    await gitTree.getByRole('button',{name:'docs/feature/browser-feature/README.md',exact:true}).click();
    await expect(page.locator('[data-git-diff]')).toContainText('External editor wins.');
    await expect(page.getByRole('dialog')).toHaveCount(0);
    const treeBounds = await gitTree.boundingBox();
    const diffBounds = await page.locator('[data-git-diff]').boundingBox();
    assert.ok(treeBounds && diffBounds && diffBounds.x >= treeBounds.x + treeBounds.width, 'Git diff stays beside the file tree');
    await gitTree.getByRole('button',{name:'docs 目录',exact:true}).click();
    await expect(gitTree.getByRole('button',{name:'docs/feature/browser-feature/README.md',exact:true})).toBeHidden();
    await gitTree.getByRole('button',{name:'docs 目录',exact:true}).click();
    writeFileSync(path,readFileSync(path,'utf8').replace('External editor wins.','Refreshed Git content.'));
    await page.getByRole('button',{name:'刷新',exact:true}).click();
    await expect(page.locator('[data-git-diff]')).toContainText('Refreshed Git content.');
    await page.keyboard.press('Escape');
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await page.getByRole('link',{name:'项目设置',exact:true}).click();
    await expect(page.getByLabel('Project ID',{exact:true})).not.toBeEditable();
    await page.getByLabel('运行超时',{exact:true}).fill('11111');
    await expect.poll(()=>readProjectConfig(root).runner.timeoutMs).toBe(11111);
    await page.getByLabel('源码目录',{exact:true}).fill('src\n');
    await expect(page.getByLabel('源码目录',{exact:true})).toHaveValue('src\n');
    // Wait for the preceding save/readback to finish before introducing an external edit.
    await expect(page.getByLabel('源码目录',{exact:true})).toHaveValue('src');
    await expect(page.getByRole('status')).toContainText('已自动保存');
    await page.getByLabel('运行超时',{exact:true}).fill('12345');
    const configPath=join(root,projectConfigPath(root));
    const config=readProjectConfig(root);
    writeProjectConfig(root,{...config,runner:{...config.runner,timeoutMs:54321}});
    const externalConfig=readFileSync(configPath,'utf8');
    await expect(page.locator('.form-error').first()).toBeVisible();
    await expect(page.getByLabel('运行超时',{exact:true})).toHaveValue('12345');
    assert.equal(readFileSync(configPath,'utf8'),externalConfig,'polled digests must not let stale config overwrite disk');
    await page.getByRole('tab',{name:'高级 JSON',exact:true}).click();
    await expect(page.getByRole('dialog',{name:'离开并丢弃未保存内容？'})).toBeVisible();
    await page.getByRole('button',{name:'丢弃并离开',exact:true}).click();
    await page.getByLabel('高级项目配置 JSON',{exact:true}).fill('{}');
    await page.getByRole('tab',{name:'常用设置',exact:true}).click();
    await expect(page.getByLabel('高级项目配置 JSON',{exact:true})).toHaveValue('{}');
    await expect(page.locator('.form-error').first()).toBeVisible();
    await page.getByRole('button',{name:'留在此页',exact:true}).click();
    await sidebar.getByRole('link',{name:'Feature',exact:true}).click();
    await expect(page.getByRole('dialog')).toBeVisible();
    await page.getByRole('button',{name:'丢弃并离开',exact:true}).click();
    await expect(navigation).toBeVisible();
    await navigation.getByRole('link',{name:'Browser authoring',exact:true}).click();
    writeFileSync(join(root,'src/demo.ts'),'// @concord-file\n// @concord-implements docs/feature/browser-feature/README.md\nexport const demo = 1;\n');
    mkdirSync(join(root,'test'),{recursive:true});
    writeFileSync(join(root,'test/demo.test.ts'),"import test from 'node:test';\n// @use-case docs/feature/browser-feature/use-case/browser-flow.md\ntest('Added browser test', () => {});\n" + Array.from({length:100},(_,index)=>`// Reading fixture ${index}\n`).join(''));
    await page.reload();
    await expect(page.getByRole('tab',{name:'测试',exact:true})).toBeVisible();
    await page.getByRole('tab',{name:'测试',exact:true}).click();
    const markerName = 'docs/feature/browser-feature/use-case/browser-flow.md#0';
    await expect(page.getByText(markerName,{exact:true})).toBeVisible();
    await page.getByRole('button',{name:'查看测试源码',exact:true}).click();
    await expect(page.getByRole('dialog')).toContainText('Added browser test');
    await page.keyboard.press('Escape');
    await page.getByRole('tab',{name:'实现',exact:true}).click();
    await page.getByRole('button',{name:/^src\/demo\.ts · 第 /}).click();
    const source=page.getByLabel('源码原文',{exact:true});
    await source.fill('export const demo = 2;\n');
    await expect.poll(()=>readFileSync(join(root,'src/demo.ts'),'utf8')).toBe('export const demo = 2;\n');
    await page.getByRole('button',{name:'Close',exact:true}).click();
    await sidebar.getByRole('link',{name:'Git 变更',exact:true}).click();
    await expect(page.getByRole('tab',{name:/文档/})).toHaveAttribute('aria-selected','true');
    await expect(page.getByRole('region',{name:'新增测试用例',exact:true})).toHaveCount(0);
    await page.getByRole('tab',{name:/测试用例/}).click();
    await expect(gitTree).toContainText(markerName);
    await expect(gitTree).not.toContainText('src/demo.ts');
    await gitTree.getByRole('button').filter({hasText:markerName}).click();
    await expect(page.locator('[data-git-diff]')).toContainText('Added browser test');
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await expect(page).toHaveURL(/line=2/);
    await expect(page.locator('[data-git-diff] #git-line-2')).toBeVisible();
    const diffScroll = page.getByTestId('git-diff-scroll');
    await diffScroll.evaluate(element => { element.scrollTop = 250; });
    await expect.poll(() => diffScroll.evaluate(element => element.scrollTop)).toBe(250);
    await page.getByRole('tab',{name:/文档/}).click();
    await gitTree.getByRole('button',{name:'docs/feature/browser-feature/README.md',exact:true}).click();
    await page.getByRole('tab',{name:/测试用例/}).click();
    await expect(gitTree.getByRole('button',{name:'test/demo.test.ts',exact:true})).toHaveAttribute('aria-current','page');
    await expect.poll(() => diffScroll.evaluate(element => element.scrollTop)).toBe(250);
    await page.getByRole('tab',{name:/文档/}).click();
    await expect(gitTree.getByRole('button',{name:'docs/feature/browser-feature/README.md',exact:true})).toHaveAttribute('aria-current','page');
    await page.getByRole('tab',{name:'分栏',exact:true}).click();
    await expect(page).toHaveURL(/view=split/);
    await page.getByRole('tab',{name:'统一',exact:true}).click();
    await expect(page).toHaveURL(/view=unified/);
    await page.goBack();
    await expect(page.getByRole('tab',{name:'分栏',exact:true})).toHaveAttribute('data-state','active');
    await page.reload();
    await expect(page.getByRole('tab',{name:'分栏',exact:true})).toHaveAttribute('data-state','active');
    await page.getByRole('tab',{name:/测试用例/}).click();
    await page.reload();
    await expect(page.locator('[data-git-diff]')).toContainText('Added browser test');
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await expect(page.getByRole('tab',{name:/测试用例/})).toHaveAttribute('aria-selected','true');
    await expect(sidebar.getByRole('link',{name:'测试',exact:true})).toHaveCount(0);
    await expect(sidebar.getByRole('link',{name:'实现',exact:true})).toHaveCount(0);
    await page.setViewportSize({width:390,height:844});
    await page.getByRole('button',{name:'内容导航',exact:true}).click();
    await expect(page.getByRole('dialog')).toContainText('test');
    await gitTree.getByRole('button',{name:'test/demo.test.ts',exact:true}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await expect(page.locator('[data-git-diff]')).toContainText('Added browser test');
    await page.getByRole('button',{name:'Toggle Sidebar',exact:true}).click();
    await expect(page.getByRole('link',{name:'Feature',exact:true})).toBeVisible();
    await page.getByRole('link',{name:'Feature',exact:true}).click();
    await expect(page.locator('[data-mobile="true"]')).toHaveCount(0);
    await page.getByRole('button',{name:'内容导航',exact:true}).click();
    await navigation.getByRole('link',{name:'Browser authoring',exact:true}).click();
    await page.getByRole('tab',{name:'Use Cases',exact:true}).click();
    await nestedCase.click();
    await expect(page.getByRole('heading',{name:'Nested browser flow',exact:true}).first()).toBeVisible();
    await expect(page.locator('[data-mobile="true"]')).toHaveCount(0);
    await page.getByRole('button',{name:'Close',exact:true}).click();
    await page.getByRole('button',{name:'新建 Feature',exact:true}).click();
    await expect(page.getByLabel('Feature ID',{exact:true})).toBeVisible();
    await page.getByRole('button',{name:'取消',exact:true}).click();
    assert.deepEqual(errors,[]);
  } finally {await browser?.close();await server?.close();rmSync(root,{recursive:true,force:true});}
});

// @use-case docs/feature/local-sdlc/use-case/plan-and-adopt-contracts.md
test('browser creates Unicode Feature and Use Case names and restores their encoded routes', async () => {
  const root = mkdtempSync(join(tmpdir(), 'concord-unicode-browser-'));
  let server: ViewServerHandle | undefined;
  let browser: Browser | undefined;
  try {
    execFileSync('git', ['init', '-q', root]);
    const repo = new LocalRepository(root, { initialize: true });
    try { initialize(repo); } finally { repo.close(); }
    server = await startViewServer({ root, host: '127.0.0.1', port: 0 });
    const executablePath = process.env.CONCORD_BROWSER_PATH ?? (existsSync('/run/current-system/sw/bin/chromium') ? '/run/current-system/sw/bin/chromium' : undefined);
    browser = await chromium.launch({ headless: true, ...(executablePath ? { executablePath } : {}), args: ['--no-sandbox'] });
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    await page.goto(`http://127.0.0.1:${server.port}/features`);
    await page.getByRole('button', { name: '新建 Feature', exact: true }).click();
    await page.getByLabel('Feature ID', { exact: true }).fill('角色NPC');
    await page.getByLabel('Feature 标题', { exact: true }).fill('角色');
    await page.getByRole('dialog').getByRole('button', { name: '创建', exact: true }).click();
    await page.getByRole('tab', { name: 'Use Cases', exact: true }).click();
    await page.getByRole('button', { name: '新建 Use Case', exact: true }).click();
    await page.getByLabel('Use Case ID', { exact: true }).fill('扩展NPC动作');
    await page.getByLabel('Use Case 标题', { exact: true }).fill('扩展 NPC 动作');
    await page.getByRole('dialog').getByRole('button', { name: '创建', exact: true }).click();
    await page.getByRole('link', { name: /扩展 NPC 动作/u }).click();
    await expect(page.getByRole('dialog')).toContainText('扩展 NPC 动作');
    assert.match(decodeURIComponent(new URL(page.url()).pathname), /角色NPC\/use-cases\/扩展NPC动作$/u);
    await page.reload();
    await expect(page.getByRole('dialog')).toContainText('扩展 NPC 动作');
    assert.match(readFileSync(join(root, 'docs/feature/角色NPC/use-case/扩展NPC动作.md'), 'utf8'), /id: 扩展NPC动作/u);
  } finally { await browser?.close(); await server?.close(); rmSync(root, { recursive: true, force: true }); }
});
