import { execFileSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { closeSync, existsSync, lstatSync, mkdirSync, openSync, readFileSync, readdirSync, renameSync, unlinkSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Effect, Schema } from 'effect';
import { AnnotatedCaseSchema, ConcordError, MemorySchema, ProjectSchema, Text, canonical, decode, digest, objectDigest, type AnnotatedCase, type DocumentRecord, type FixedProof, type ProjectConfig, type Repository, type Resolution } from './shared.js';
import { hasSuccessfulOwnedProcessResult, runOwnedProcess, type OwnedProcessResult } from './owned-process.js';
import { loadDocuments, resolveReference } from './documents.js';
import { parseReference } from './refs.js';

const MAX_EVIDENCE_BYTES = 1024 * 1024;
const OPAQUE_ID = /^ccev_[0-9a-f]{32}$/u;
const INITIAL_INDEX = new Set(['docs/feature/README.md', 'docs/roadmap/README.md', 'docs/design/README.md', 'docs/research/README.md', 'docs/issues/README.md', 'memory/README.md']);
const safeEnvironment = (): NodeJS.ProcessEnv => { const env = { ...process.env }; for (const key of Object.keys(env)) if (key.startsWith('GIT_')) delete env[key]; return env; };
const iso = () => new Date().toISOString();

export const EvidenceSchema = Schema.Struct({
  id: Schema.String.check(Schema.isPattern(OPAQUE_ID)), format: Schema.Literal('concord.command-evidence/v1'), scope: Schema.Literal('command'),
  selectedCaseId: Text, projectId: Text, root: Text, implementationDigest: Text, definitionDigest: Text, contractDigest: Text, candidateDigest: Text,
  problemEpochs: Schema.Record(Text, Schema.Int.check(Schema.isGreaterThanOrEqualTo(0))), argv: Schema.NonEmptyArray(Text),
  startedAt: Text, finishedAt: Text, commandOutcome: Schema.Literals(['pass', 'fail', 'invalid']), execution: Schema.Literals(['nonzero', 'zero', 'skipped', 'unknown']),
  exitCode: Schema.NullOr(Schema.Int), signal: Schema.NullOr(Text), timedOut: Schema.Boolean, cancelled: Schema.Boolean, cleanupOk: Schema.Boolean,
  stdoutDigest: Text, stderrDigest: Text, integrity: Text,
});
export type Evidence = typeof EvidenceSchema.Type;
const decodeEvidence = (value: unknown, source: string): Evidence => decode(EvidenceSchema as unknown as Schema.ConstraintDecoder<Evidence, never>, value, source);

function fail(code: string, message: string): never { throw new ConcordError(code, message); }
function regular(path: string): void { try { const stat = lstatSync(path); if (!stat.isFile()) fail('UnsafePath', `Expected a regular file: ${path}`); } catch (cause) { if (cause instanceof ConcordError) throw cause; fail('InvalidFile', `Required file does not exist: ${path}`); } }
function implementationDigest(): string {
  const root = dirname(fileURLToPath(import.meta.url)); const entries: { path: string; digest: string }[] = [];
  const walk = (directory: string) => { for (const name of readdirSync(directory).sort()) { const path = join(directory, name); const stat = lstatSync(path); if (stat.isSymbolicLink()) fail('UnsafeToolInstallation', `Concord implementation contains a symbolic link: ${path}`); if (stat.isDirectory()) walk(path); else if (stat.isFile() && /\.(?:[cm]?js)$/u.test(name)) entries.push({ path: relative(root, path), digest: digest(readFileSync(path)) }); } };
  walk(root); return objectDigest(entries);
}
function git(repo: Repository, args: readonly string[]): string { try { return execFileSync('git', ['-C', repo.root, ...args], { env: safeEnvironment(), encoding: 'buffer', stdio: ['ignore', 'pipe', 'pipe'], maxBuffer: 32 * 1024 * 1024 }).toString('utf8'); } catch { return fail('GitFailed', 'Could not inspect the current Git worktree'); } }
function nul(value: string): string[] { return value.split('\0').filter(Boolean); }
function currentCandidate(repo: Repository, documents = loadDocuments(repo)): string {
  const owners = new Set([...documents.map((document) => document.path), ...INITIAL_INDEX]);
  const tracked = nul(git(repo, ['ls-files', '-z'])); const untracked = nul(git(repo, ['ls-files', '--others', '--exclude-standard', '-z']));
  const deleted = new Set(nul(git(repo, ['ls-files', '--deleted', '-z']))); const paths = [...new Set([...tracked, ...untracked])].sort();
  const entries = paths.filter((path) => !owners.has(path) && path !== 'concord.json').map((path) => {
    const target = repo.absolute(path); if (deleted.has(path) || !existsSync(target)) return { path, state: 'deleted' as const };
    regular(target); return { path, state: 'present' as const, digest: digest(readFileSync(target)) };
  });
  return objectDigest(entries);
}
export const candidateDigest = currentCandidate;
function documentFor(repo: Repository, documents: readonly DocumentRecord[], reference: string, kinds: readonly ('feature' | 'use-case' | 'memory')[]): DocumentRecord { return resolveReference(repo, documents, reference, kinds); }
function documentDigest(repo: Repository, document: DocumentRecord, reference: string): string { const target = parseReference(reference).path; const source = repo.read(target); if (source === undefined) fail('ReferenceNotFound', `Contract source disappeared: ${reference}`); return objectDigest({ owner: { path: document.path, metadata: document.metadata, body: document.body }, reference, source: digest(source) }); }
function currentConfig(repo: Repository): ProjectConfig { const source = repo.read('concord.json'); if (source === undefined) fail('ProjectNotFound', 'concord.json disappeared while issuing evidence'); try { return decode(ProjectSchema, JSON.parse(source), 'concord.json'); } catch (cause) { throw cause instanceof ConcordError ? cause : new ConcordError('InvalidData', 'concord.json changed during evidence execution'); } }
function buildDefinition(repo: Repository, selected: AnnotatedCase, config: ProjectConfig, documents: readonly DocumentRecord[]): { readonly digest: string; readonly argv: readonly string[] } {
  if (selected.status !== 'active' || selected.skipped) fail('CaseNotRunnable', 'Retired or known skipped/todo test cases cannot issue fixed evidence');
  const owners = new Set(documents.map((document) => document.path));
  const test = repo.absolute(selected.file); regular(test); if (owners.has(selected.file)) fail('InvalidDefinition', 'A Concord Markdown owner cannot be a test file');
  const sourceFiles = config.runner.sourceFiles.map((path) => { if (owners.has(path)) fail('InvalidDefinition', 'A Concord Markdown owner cannot be a runner source file'); const target = repo.absolute(path); regular(target); return { path, digest: digest(readFileSync(target)) }; });
  const runner = config.runner;
  let argv: readonly string[];
  if (runner.kind === 'node-test') { if (selected.framework !== 'node:test') fail('UnsupportedRunner', 'The node-test runner only supports node:test annotations'); argv = ['node', '--test', '--test-reporter=tap', '--test-name-pattern', `^${selected.name.replace(/[\\^$.*+?()[\]{}|]/gu, '\\$&')}$`, selected.file]; }
  else {
    const replacement: Record<string, string> = { '{file}': selected.file, '{name}': selected.name, '{pattern}': `^${selected.name.replace(/[\\^$.*+?()[\]{}|]/gu, '\\$&')}$` };
    argv = runner.argv.map((part) => { if (/\{(?:file|name|pattern)\}/u.test(part) && !(part in replacement)) fail('InvalidRunner', 'Runner placeholders must occupy an entire argv element'); if (/\{[^}]*\}/u.test(part) && !(part in replacement)) fail('InvalidRunner', `Unknown runner placeholder: ${part}`); return replacement[part] ?? part; });
  }
  return { digest: objectDigest({ annotation: selected, testFile: { path: selected.file, digest: digest(readFileSync(test)) }, runner, sourceFiles }), argv };
}
function safeEvidencePath(repo: Repository, id: string): string { if (!OPAQUE_ID.test(id)) fail('InvalidEvidenceId', 'Evidence IDs are opaque Concord IDs'); const directory = resolve(repo.privateDir, 'evidence'); const root = resolve(repo.privateDir); if (!directory.startsWith(`${root}${sep}`)) fail('UnsafePath', 'Evidence directory escaped repository private state'); for (const part of [root, directory]) { if (existsSync(part) && lstatSync(part).isSymbolicLink()) fail('UnsafePath', `Symbolic links are not permitted: ${part}`); } return join(directory, `${id}.json`); }
function store(repo: Repository, evidence: Evidence): void { const path = safeEvidencePath(repo, evidence.id); const directory = dirname(path); mkdirSync(directory, { recursive: true, mode: 0o700 }); if (lstatSync(directory).isSymbolicLink()) fail('UnsafePath', 'Evidence directory is a symbolic link'); const source = `${canonical(evidence)}\n`; const temporary = `${path}.${process.pid}.${randomBytes(8).toString('hex')}.tmp`; let fd: number | undefined; try { fd = openSync(temporary, 'wx', 0o600); writeFileSync(fd, source); closeSync(fd); fd = undefined; renameSync(temporary, path); } finally { if (fd !== undefined) closeSync(fd); try { unlinkSync(temporary); } catch { /* renamed or absent */ } } }
export function readEvidence(repo: Repository, id: string): Evidence { const path = safeEvidencePath(repo, id); regular(path); let value: unknown; try { if (lstatSync(path).size > MAX_EVIDENCE_BYTES) fail('InvalidEvidence', 'Evidence receipt exceeds its size limit'); value = JSON.parse(readFileSync(path, 'utf8')); } catch (cause) { if (cause instanceof ConcordError) throw cause; fail('InvalidEvidence', `Cannot decode evidence receipt: ${cause instanceof Error ? cause.message : String(cause)}`); } const evidence = decodeEvidence(value, `evidence ${id}`); if (evidence.id !== id) fail('EvidenceIntegrity', 'Evidence receipt ID does not match its opaque filename'); const { integrity, ...unsigned } = evidence; if (integrity !== objectDigest(unsigned)) fail('EvidenceIntegrity', 'Evidence receipt failed its accidental-corruption integrity check'); return evidence; }
function observed(result: OwnedProcessResult, node: boolean): { execution: Evidence['execution']; outcome: Evidence['commandOutcome'] } {
  if (result.outputLimitExceeded || result.timedOut || result.cancelled || result.signal !== null || result.error !== undefined) return { execution: 'unknown', outcome: 'invalid' };
  if (!node) return { execution: 'unknown', outcome: result.exitCode === 0 ? 'pass' : 'fail' };
  const tap = `${result.stdout}\n${result.stderr}`;
  const count = (name: string): number | undefined => { const values = [...tap.matchAll(new RegExp(`^# ${name} (\\d+)\\s*$`, 'gmu'))].map((match) => Number(match[1])); return values.at(-1); };
  const tests = count('tests'), pass = count('pass'), failed = count('fail'), skipped = count('skipped'), todo = count('todo');
  if ([tests, pass, failed, skipped, todo].some((value) => value === undefined) || tests === undefined || pass === undefined || failed === undefined || skipped === undefined || todo === undefined || pass + failed + skipped + todo !== tests) return { execution: 'unknown', outcome: 'invalid' };
  const execution: Evidence['execution'] = tests === 0 ? 'zero' : pass + failed > 0 ? 'nonzero' : skipped + todo === tests ? 'skipped' : 'unknown';
  return { execution, outcome: execution === 'zero' || execution === 'skipped' || execution === 'unknown' ? 'invalid' : result.exitCode === 0 ? 'pass' : 'fail' };
}
export const runCase = (repo: Repository, selected: AnnotatedCase, documents: readonly DocumentRecord[]): Effect.Effect<Evidence, ConcordError, import('./owned-process.js').OwnedProcess> => Effect.suspend(() => {
  const annotation = decode(AnnotatedCaseSchema, selected, 'selected test case'); const beforeDocuments = loadDocuments(repo); const beforeConfig = currentConfig(repo); const definition = buildDefinition(repo, annotation, beforeConfig, beforeDocuments); const contract = documentFor(repo, beforeDocuments, annotation.contract, ['feature', 'use-case']); const problems = annotation.regressions.map((ref) => documentFor(repo, beforeDocuments, ref, ['memory'])).filter((doc) => doc.metadata.kind === 'memory' && doc.metadata.memoryKind === 'problem');
  const epochs: Record<string, number> = {}; for (const problem of problems) { const metadata = decode(MemorySchema, problem.metadata, problem.path); epochs[problem.path] = metadata.epoch; }
  const contractDigest = documentDigest(repo, contract, annotation.contract); const candidate = currentCandidate(repo, beforeDocuments); const implementation = implementationDigest(); const startedAt = iso();
  return runOwnedProcess(definition.argv, { cwd: repo.root, env: safeEnvironment(), timeoutMs: beforeConfig.runner.timeoutMs }).pipe(Effect.map((result) => {
    const afterDocuments = loadDocuments(repo); const afterConfig = currentConfig(repo); const afterProblems = annotation.regressions.map((ref) => documentFor(repo, afterDocuments, ref, ['memory'])).filter((doc) => doc.metadata.kind === 'memory' && doc.metadata.memoryKind === 'problem');
    const afterEpochs = Object.fromEntries(afterProblems.map((problem) => [problem.path, decode(MemorySchema, problem.metadata, problem.path).epoch])); const afterContract = documentFor(repo, afterDocuments, annotation.contract, ['feature', 'use-case']);
    const stable = candidate === currentCandidate(repo, afterDocuments) && implementation === implementationDigest() && canonical(beforeConfig) === canonical(afterConfig) && definition.digest === buildDefinition(repo, annotation, afterConfig, afterDocuments).digest && contractDigest === documentDigest(repo, afterContract, annotation.contract) && canonical(epochs) === canonical(afterEpochs);
    const state = observed(result, beforeConfig.runner.kind === 'node-test'); const outcome = stable ? state.outcome : 'invalid'; const unsigned = { id: `ccev_${randomBytes(16).toString('hex')}`, format: 'concord.command-evidence/v1' as const, scope: 'command' as const, selectedCaseId: annotation.id, projectId: beforeConfig.projectId, root: repo.root, implementationDigest: implementation, definitionDigest: definition.digest, contractDigest, candidateDigest: candidate, problemEpochs: epochs, argv: [...definition.argv], startedAt, finishedAt: iso(), commandOutcome: outcome, execution: state.execution, exitCode: result.exitCode, signal: result.signal, timedOut: result.timedOut, cancelled: result.cancelled, cleanupOk: hasSuccessfulOwnedProcessResult(result) || (!result.processGroupOwned || result.groupCleanup.gone === true), stdoutDigest: digest(result.stdout), stderrDigest: digest(result.stderr) }; const evidence = decodeEvidence({ ...unsigned, integrity: objectDigest(unsigned) }, 'issued evidence'); store(repo, evidence); return evidence;
  }), Effect.catch((cause) => Effect.fail(cause instanceof ConcordError ? cause : new ConcordError('CommandFailed', cause instanceof Error ? cause.message : String(cause)))));
}).pipe(Effect.scoped);
export function verifyFixedEvidence(repo: Repository, documents: readonly DocumentRecord[], cases: readonly AnnotatedCase[], problem: DocumentRecord, redId: string, greenId: string): FixedProof {
  const currentDocuments = loadDocuments(repo); const currentProblem = currentDocuments.find((document) => document.path === problem.path); if (currentProblem === undefined) fail('ProblemNotOpen', 'Problem disappeared while verifying fixed evidence'); const meta = decode(MemorySchema, currentProblem.metadata, currentProblem.path); if (meta.memoryKind !== 'problem' || meta.state !== 'open') fail('ProblemNotOpen', 'Fixed evidence requires an open Problem'); const config = currentConfig(repo); const red = readEvidence(repo, redId); const green = readEvidence(repo, greenId); if (red.selectedCaseId !== green.selectedCaseId || red.projectId !== config.projectId || green.projectId !== config.projectId || red.root !== repo.root || green.root !== repo.root || red.implementationDigest !== implementationDigest() || green.implementationDigest !== implementationDigest()) fail('EvidenceMismatch', 'Evidence receipts do not share this current worktree and Concord implementation'); const selected = cases.find((item) => item.id === red.selectedCaseId); if (selected === undefined || selected.status !== 'active' || !selected.regressions.includes(currentProblem.path) && !selected.regressions.includes(meta.id)) fail('EvidenceMismatch', 'The current active annotation does not regress this Problem'); const definition = buildDefinition(repo, selected, config, currentDocuments); const contract = documentFor(repo, currentDocuments, selected.contract, ['feature', 'use-case']); const expectedEpoch = meta.epoch; for (const evidence of [red, green]) if (evidence.definitionDigest !== definition.digest || evidence.contractDigest !== documentDigest(repo, contract, selected.contract) || evidence.problemEpochs[currentProblem.path] !== expectedEpoch) fail('EvidenceStale', 'Evidence definition, contract, or Problem epoch is no longer current'); if (red.commandOutcome !== 'fail' || red.execution === 'zero' || red.execution === 'skipped' || red.exitCode === 0 || red.timedOut || red.cancelled || red.signal !== null || !red.cleanupOk) fail('InvalidRedEvidence', 'Red evidence must be a normal nonzero command result with confirmed cleanup'); if (green.commandOutcome !== 'pass' || green.execution === 'zero' || green.execution === 'skipped' || green.exitCode !== 0 || green.timedOut || green.cancelled || green.signal !== null || !green.cleanupOk) fail('InvalidGreenEvidence', 'Green evidence must be a normal successful command result with confirmed cleanup'); if (Date.parse(red.finishedAt) > Date.parse(green.startedAt) || Number.isNaN(Date.parse(red.finishedAt)) || Number.isNaN(Date.parse(green.startedAt))) fail('EvidenceOrder', 'Red evidence must not follow green evidence'); const current = currentCandidate(repo, currentDocuments); if (green.candidateDigest !== current) fail('EvidenceStale', 'Green evidence does not match the current implementation candidate'); return { red: red.id, green: green.id, selectedCaseId: selected.id, epoch: expectedEpoch };
}
export function inspectResolutionEvidence(repo: Repository, resolution: Resolution): object { if (resolution.kind !== 'fixed' || resolution.red === undefined || resolution.green === undefined) return { availability: 'unavailable', evidenceLevel: resolution.evidenceLevel }; try { const red = readEvidence(repo, resolution.red); const green = readEvidence(repo, resolution.green); return { availability: red.commandOutcome === 'invalid' || green.commandOutcome === 'invalid' ? 'invalid' : 'available', evidenceLevel: 'command', red: red.id, green: green.id, note: 'Historical command evidence; not current verification.' }; } catch (cause) { return { availability: 'unavailable', evidenceLevel: 'command', note: cause instanceof ConcordError && cause.code === 'EvidenceIntegrity' ? 'Evidence receipt is invalid.' : 'Historical private evidence is unavailable; not current verification.' }; } }
